//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MegaApp.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been updated. Do you want to check the new account details?.
        /// </summary>
        public static string AccountUpdate {
            get {
                return ResourceManager.GetString("AccountUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated account.
        /// </summary>
        public static string AccountUpdated_Title {
            get {
                return ResourceManager.GetString("AccountUpdated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree with our Terms of Service.
        /// </summary>
        public static string AgreeTermsOfService {
            get {
                return ResourceManager.GetString("AgreeTermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is already confirmed. You can now login..
        /// </summary>
        public static string AlreadyConfirmedAccount {
            get {
                return ResourceManager.GetString("AlreadyConfirmedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already confirmed.
        /// </summary>
        public static string AlreadyConfirmedAccount_Title {
            get {
                return ResourceManager.GetString("AlreadyConfirmedAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your MEGA subscription purchase has failed because you already have purchased this item..
        /// </summary>
        public static string AlreadyPurchased {
            get {
                return ResourceManager.GetString("AlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already purchased.
        /// </summary>
        public static string AlreadyPurchased_Title {
            get {
                return ResourceManager.GetString("AlreadyPurchased_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you agree, the current account will be logged out and all Offline data will be erased. Do you want to continue?.
        /// </summary>
        public static string AM_AlreadyLoggedInAlert {
            get {
                return ResourceManager.GetString("AM_AlreadyLoggedInAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in with another account.
        /// </summary>
        public static string AM_AlreadyLoggedInAlert_Title {
            get {
                return ResourceManager.GetString("AM_AlreadyLoggedInAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to cancel your MEGA subscription. Please let us know if there is anything we can do to help change your mind..
        /// </summary>
        public static string AM_CancelSubscription {
            get {
                return ResourceManager.GetString("AM_CancelSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your feedback! Are you sure you want to cancel your MEGA subscription?.
        /// </summary>
        public static string AM_CancelSubscriptionConfirmation {
            get {
                return ResourceManager.GetString("AM_CancelSubscriptionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy item. Please try again..
        /// </summary>
        public static string AM_CopyFailed {
            get {
                return ResourceManager.GetString("AM_CopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy failed.
        /// </summary>
        public static string AM_CopyFailed_Title {
            get {
                return ResourceManager.GetString("AM_CopyFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy the MEGA link to your clipboard..
        /// </summary>
        public static string AM_CopyLinkToClipboardFailed {
            get {
                return ResourceManager.GetString("AM_CopyLinkToClipboardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error copying link.
        /// </summary>
        public static string AM_CopyLinkToClipboardFailed_Title {
            get {
                return ResourceManager.GetString("AM_CopyLinkToClipboardFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode is enabled. Do you want to disable it?.
        /// </summary>
        public static string AM_DebugModeEnabled_Message {
            get {
                return ResourceManager.GetString("AM_DebugModeEnabled_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode.
        /// </summary>
        public static string AM_DebugModeEnabled_Title {
            get {
                return ResourceManager.GetString("AM_DebugModeEnabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access this folder/file, you will need its Decryption key. If you do not have the key, contact the creator of the link..
        /// </summary>
        public static string AM_DecryptionKeyAlertMessage {
            get {
                return ResourceManager.GetString("AM_DecryptionKeyAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter decryption key.
        /// </summary>
        public static string AM_DecryptionKeyAlertTitle {
            get {
                return ResourceManager.GetString("AM_DecryptionKeyAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid decryption key.
        /// </summary>
        public static string AM_DecryptionKeyNotValid {
            get {
                return ResourceManager.GetString("AM_DecryptionKeyNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete settings. Please try again. [{0}].
        /// </summary>
        public static string AM_DeleteSettingsFailed {
            get {
                return ResourceManager.GetString("AM_DeleteSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting settings.
        /// </summary>
        public static string AM_DeleteSettingsFailed_Title {
            get {
                return ResourceManager.GetString("AM_DeleteSettingsFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log ({0}) will be deleted from the Offline section..
        /// </summary>
        public static string AM_DisableDebugMode_Message {
            get {
                return ResourceManager.GetString("AM_DisableDebugMode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable DEBUG mode.
        /// </summary>
        public static string AM_DisableDebugMode_Title {
            get {
                return ResourceManager.GetString("AM_DisableDebugMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have access to the selected download path. Please select a different download path and try again..
        /// </summary>
        public static string AM_DowloadPathUnauthorizedAccess {
            get {
                return ResourceManager.GetString("AM_DowloadPathUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        public static string AM_DowloadPathUnauthorizedAccess_Title {
            get {
                return ResourceManager.GetString("AM_DowloadPathUnauthorizedAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download the file. Please try again..
        /// </summary>
        public static string AM_DownloadNodeFailedNoErrorCode {
            get {
                return ResourceManager.GetString("AM_DownloadNodeFailedNoErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A log will be created in the Offline section ({0})..
        /// </summary>
        public static string AM_EnableDebugMode_Message {
            get {
                return ResourceManager.GetString("AM_EnableDebugMode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable DEBUG mode.
        /// </summary>
        public static string AM_EnableDebugMode_Title {
            get {
                return ResourceManager.GetString("AM_EnableDebugMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This could be due to the following reasons:
        ///- The file has been removed because of a ToS/AUP violation.
        ///- Invalid URL – the link you are trying to access does not exist.
        ///- The file has been deleted by the user..
        /// </summary>
        public static string AM_FileLinkUnavailable {
            get {
                return ResourceManager.GetString("AM_FileLinkUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This could be due to the following reasons:
        ///- The folder link has been removed because of a ToS/AUP violation.
        ///- Invalid URL – the link you are trying to access does not exist.
        ///- The folder link has been deleted by the user..
        /// </summary>
        public static string AM_FolderLinkUnavailable {
            get {
                return ResourceManager.GetString("AM_FolderLinkUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File import failed [{0}].
        /// </summary>
        public static string AM_ImportFileFailed {
            get {
                return ResourceManager.GetString("AM_ImportFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File import failed.
        /// </summary>
        public static string AM_ImportFileFailedNoErrorCode {
            get {
                return ResourceManager.GetString("AM_ImportFileFailedNoErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid link.
        /// </summary>
        public static string AM_InvalidLink {
            get {
                return ResourceManager.GetString("AM_InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable link.
        /// </summary>
        public static string AM_LinkUnavailableTitle {
            get {
                return ResourceManager.GetString("AM_LinkUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load.
        /// </summary>
        public static string AM_LoadFailed_Title {
            get {
                return ResourceManager.GetString("AM_LoadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load incoming shared items from MEGA. Please try again or click on refresh..
        /// </summary>
        public static string AM_LoadInSharesFailed {
            get {
                return ResourceManager.GetString("AM_LoadInSharesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load outgoing shared items from MEGA. Please try again or click on refresh..
        /// </summary>
        public static string AM_LoadOutSharesFailed {
            get {
                return ResourceManager.GetString("AM_LoadOutSharesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load settings. Please try again. [{0}].
        /// </summary>
        public static string AM_LoadSettingsFailed {
            get {
                return ResourceManager.GetString("AM_LoadSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings.
        /// </summary>
        public static string AM_LoadSettingsFailed_Title {
            get {
                return ResourceManager.GetString("AM_LoadSettingsFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open link failed [{0}].
        /// </summary>
        public static string AM_OpenLinkFailed {
            get {
                return ResourceManager.GetString("AM_OpenLinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open link failed.
        /// </summary>
        public static string AM_OpenLinkFailed_Title {
            get {
                return ResourceManager.GetString("AM_OpenLinkFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to prepare file(s) for upload. Please try again..
        /// </summary>
        public static string AM_PrepareFilesForUploadFailed {
            get {
                return ResourceManager.GetString("AM_PrepareFilesForUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error preparing file(s).
        /// </summary>
        public static string AM_PrepareFilesForUploadFailed_Title {
            get {
                return ResourceManager.GetString("AM_PrepareFilesForUploadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy Recovery Key to clipboard. Please try again..
        /// </summary>
        public static string AM_RecoveryKeyClipboardFailed {
            get {
                return ResourceManager.GetString("AM_RecoveryKeyClipboardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard failed.
        /// </summary>
        public static string AM_RecoveryKeyClipboardFailed_Title {
            get {
                return ResourceManager.GetString("AM_RecoveryKeyClipboardFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Key copied to clipboard.
        /// </summary>
        public static string AM_RecoveryKeyCopied {
            get {
                return ResourceManager.GetString("AM_RecoveryKeyCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Key copied.
        /// </summary>
        public static string AM_RecoveryKeyCopied_Title {
            get {
                return ResourceManager.GetString("AM_RecoveryKeyCopied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to share item(s) from MEGA. Please try again..
        /// </summary>
        public static string AM_ShareFromMegaFailed_Message {
            get {
                return ResourceManager.GetString("AM_ShareFromMegaFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sharing item(s).
        /// </summary>
        public static string AM_ShareFromMegaFailed_Title {
            get {
                return ResourceManager.GetString("AM_ShareFromMegaFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item shared with the Windows Phone app of MEGA..
        /// </summary>
        public static string AM_ShareItemFromMega_Message {
            get {
                return ResourceManager.GetString("AM_ShareItemFromMega_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item shared from MEGA.
        /// </summary>
        public static string AM_ShareItemFromMega_Title {
            get {
                return ResourceManager.GetString("AM_ShareItemFromMega_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items shared with the Windows Phone app of MEGA..
        /// </summary>
        public static string AM_ShareMultipleItemsFromMega_Message {
            get {
                return ResourceManager.GetString("AM_ShareMultipleItemsFromMega_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items shared from MEGA.
        /// </summary>
        public static string AM_ShareMultipleItemsFromMega_Title {
            get {
                return ResourceManager.GetString("AM_ShareMultipleItemsFromMega_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Auto Camera Upload background task has failed. You can re-enable it on the settings page..
        /// </summary>
        public static string AutoCameraUploadFailed {
            get {
                return ResourceManager.GetString("AutoCameraUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Camera Upload failed.
        /// </summary>
        public static string AutoCameraUploadFailed_Title {
            get {
                return ResourceManager.GetString("AutoCameraUploadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents for MEGA have been disabled by the user.
        /// </summary>
        public static string BackgroundAgentDisabled {
            get {
                return ResourceManager.GetString("BackgroundAgentDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents disabled.
        /// </summary>
        public static string BackgroundAgentDisabled_Title {
            get {
                return ResourceManager.GetString("BackgroundAgentDisabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache has been succesfully cleared.
        /// </summary>
        public static string CacheCleared {
            get {
                return ResourceManager.GetString("CacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache cleared.
        /// </summary>
        public static string CacheCleared_Title {
            get {
                return ResourceManager.GetString("CacheCleared_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order for the automatic Camera Uploads to work correctly, you need to enable the option &quot;Stay logged in&quot;. Do you want to enable this option?.
        /// </summary>
        public static string CameraUploadNeedsStayLoggedIn {
            get {
                return ResourceManager.GetString("CameraUploadNeedsStayLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Camera Uploads prerequisites.
        /// </summary>
        public static string CameraUploadNeedsStayLoggedIn_Title {
            get {
                return ResourceManager.GetString("CameraUploadNeedsStayLoggedIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Subscription.
        /// </summary>
        public static string CancelSubscription_Title {
            get {
                return ResourceManager.GetString("CancelSubscription_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription has not been canceled correctly. Please contact support@mega.nz to cancel your subscription..
        /// </summary>
        public static string CancelSubscriptionFailed {
            get {
                return ResourceManager.GetString("CancelSubscriptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription cancellation failed.
        /// </summary>
        public static string CancelSubscriptionFailed_Title {
            get {
                return ResourceManager.GetString("CancelSubscriptionFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription has been cancelled..
        /// </summary>
        public static string CancelSubscriptionSuccessfully {
            get {
                return ResourceManager.GetString("CancelSubscriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription cancelled.
        /// </summary>
        public static string CancelSubscriptionSuccessfully_Title {
            get {
                return ResourceManager.GetString("CancelSubscriptionSuccessfully_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to capture photo. Please, try again [{0}].
        /// </summary>
        public static string CapturePhotoFailed {
            get {
                return ResourceManager.GetString("CapturePhotoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo capture failed.
        /// </summary>
        public static string CapturePhotoFailed_Title {
            get {
                return ResourceManager.GetString("CapturePhotoFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to capture photo or video. Please, try again [{0}].
        /// </summary>
        public static string CapturePhotoVideoFailed {
            get {
                return ResourceManager.GetString("CapturePhotoVideoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo/video capture failed.
        /// </summary>
        public static string CapturePhotoVideoFailed_Title {
            get {
                return ResourceManager.GetString("CapturePhotoVideoFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to capture video. Please, try again [{0}].
        /// </summary>
        public static string CaptureVideoFailed {
            get {
                return ResourceManager.GetString("CaptureVideoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video capture failed.
        /// </summary>
        public static string CaptureVideoFailed_Title {
            get {
                return ResourceManager.GetString("CaptureVideoFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change password. Please try again..
        /// </summary>
        public static string ChangePasswordFailed {
            get {
                return ResourceManager.GetString("ChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clear the rubbish bin. Please try again..
        /// </summary>
        public static string CleanRubbishBinFailed {
            get {
                return ResourceManager.GetString("CleanRubbishBinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete all files from the rubbish bin?.
        /// </summary>
        public static string CleanRubbishBinQuestion {
            get {
                return ResourceManager.GetString("CleanRubbishBinQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rubbish bin has been cleared successfully..
        /// </summary>
        public static string CleanRubbishBinSuccess {
            get {
                return ResourceManager.GetString("CleanRubbishBinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to close the session. Please try again. [{0}].
        /// </summary>
        public static string CloseAllSessionsFailed {
            get {
                return ResourceManager.GetString("CloseAllSessionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remaining sessions were successfully closed..
        /// </summary>
        public static string CloseAllSessionsSuccess {
            get {
                return ResourceManager.GetString("CloseAllSessionsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to close the session. Please try again. [{0}].
        /// </summary>
        public static string CloseSessionFailed {
            get {
                return ResourceManager.GetString("CloseSessionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has been successfully closed..
        /// </summary>
        public static string CloseSessionSucces {
            get {
                return ResourceManager.GetString("CloseSessionSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to confirm account. Please try again. [{0}].
        /// </summary>
        public static string ConfirmAccountFailed {
            get {
                return ResourceManager.GetString("ConfirmAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account confirmation failed.
        /// </summary>
        public static string ConfirmAccountFailed_Title {
            get {
                return ResourceManager.GetString("ConfirmAccountFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created, confirmed and activated. You will be logged in automatically..
        /// </summary>
        public static string ConfirmAccountSucces {
            get {
                return ResourceManager.GetString("ConfirmAccountSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activated.
        /// </summary>
        public static string ConfirmAccountSucces_Title {
            get {
                return ResourceManager.GetString("ConfirmAccountSucces_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your e-mail and click the link to login and confirm your account.
        /// </summary>
        public static string ConfirmNeeded {
            get {
                return ResourceManager.GetString("ConfirmNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation needed.
        /// </summary>
        public static string ConfirmNeeded_Title {
            get {
                return ResourceManager.GetString("ConfirmNeeded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy the selected file: [{0}].
        /// </summary>
        public static string CopyFileFailed {
            get {
                return ResourceManager.GetString("CopyFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error copying file.
        /// </summary>
        public static string CopyFileFailed_Title {
            get {
                return ResourceManager.GetString("CopyFileFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to copy this file type to the destination folder. Are you trying to save/copy a file of an unsupported type to an SD card?Please try to save/copy the file to the your device&apos;s internal memory instead..
        /// </summary>
        public static string CopyFileUnauthorizedAccessException {
            get {
                return ResourceManager.GetString("CopyFileUnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        public static string CopyFileUnauthorizedAccessException_Title {
            get {
                return ResourceManager.GetString("CopyFileUnauthorizedAccessException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA Cloud Drive account creation failed. Please try again. [{0}].
        /// </summary>
        public static string CreateAccountFailed {
            get {
                return ResourceManager.GetString("CreateAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation failed.
        /// </summary>
        public static string CreateAccountFailed_Title {
            get {
                return ResourceManager.GetString("CreateAccountFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create folder.
        /// </summary>
        public static string CreateFolderFailed {
            get {
                return ResourceManager.GetString("CreateFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder creation failed.
        /// </summary>
        public static string CreateFolderFailed_Title {
            get {
                return ResourceManager.GetString("CreateFolderFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder created successfully.
        /// </summary>
        public static string CreateFolderSuccess {
            get {
                return ResourceManager.GetString("CreateFolderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder created.
        /// </summary>
        public static string CreateFolderSuccess_Title {
            get {
                return ResourceManager.GetString("CreateFolderSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit card information is not correct. The credit card will not be charged..
        /// </summary>
        public static string CreditCardStoreFailed {
            get {
                return ResourceManager.GetString("CreditCardStoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing credit card failed.
        /// </summary>
        public static string CreditCardStoreFailed_Title {
            get {
                return ResourceManager.GetString("CreditCardStoreFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current PIN lock is not correct or does not match.
        /// </summary>
        public static string CurrentPinLockCodeDoNotMatch {
            get {
                return ResourceManager.GetString("CurrentPinLockCodeDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current PIN lock no match.
        /// </summary>
        public static string CurrentPinLockCodeDoNotMatch_Title {
            get {
                return ResourceManager.GetString("CurrentPinLockCodeDoNotMatch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove the contact {0}. Please try again. [{0}].
        /// </summary>
        public static string DeleteContactFailed {
            get {
                return ResourceManager.GetString("DeleteContactFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove the contact.
        /// </summary>
        public static string DeleteContactFailed_Title {
            get {
                return ResourceManager.GetString("DeleteContactFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the contact {0}?.
        /// </summary>
        public static string DeleteContactQuestion {
            get {
                return ResourceManager.GetString("DeleteContactQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove contact?.
        /// </summary>
        public static string DeleteContactQuestion_Title {
            get {
                return ResourceManager.GetString("DeleteContactQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0} contacts?.
        /// </summary>
        public static string DeleteMultipleContactsQuestion {
            get {
                return ResourceManager.GetString("DeleteMultipleContactsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove contacts?.
        /// </summary>
        public static string DeleteMultipleContactsQuestion_Title {
            get {
                return ResourceManager.GetString("DeleteMultipleContactsQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete item. Please try again [{0}].
        /// </summary>
        public static string DeleteNodeFailed {
            get {
                return ResourceManager.GetString("DeleteNodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed.
        /// </summary>
        public static string DeleteNodeFailed_Title {
            get {
                return ResourceManager.GetString("DeleteNodeFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete {0}?.
        /// </summary>
        public static string DeleteNodeQuestion {
            get {
                return ResourceManager.GetString("DeleteNodeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item?.
        /// </summary>
        public static string DeleteNodeQuestion_Title {
            get {
                return ResourceManager.GetString("DeleteNodeQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected over {0} items ({1}) to download. Do you want to proceed?.
        /// </summary>
        public static string DownloadLimitMessage {
            get {
                return ResourceManager.GetString("DownloadLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download count.
        /// </summary>
        public static string DownloadLimitMessage_Title {
            get {
                return ResourceManager.GetString("DownloadLimitMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve a download link. Please try again..
        /// </summary>
        public static string DownloadLinkFailed {
            get {
                return ResourceManager.GetString("DownloadLinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving link failed.
        /// </summary>
        public static string DownloadLinkFailed_Title {
            get {
                return ResourceManager.GetString("DownloadLinkFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download file. Please try again. [{0}].
        /// </summary>
        public static string DownloadNodeFailed {
            get {
                return ResourceManager.GetString("DownloadNodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        public static string DownloadNodeFailed_Title {
            get {
                return ResourceManager.GetString("DownloadNodeFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve files and folders from MEGA. Please try again..
        /// </summary>
        public static string FetchingNodesFailed {
            get {
                return ResourceManager.GetString("FetchingNodesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching data failed.
        /// </summary>
        public static string FetchingNodesFailed_Title {
            get {
                return ResourceManager.GetString("FetchingNodesFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the selected file.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFound_Title {
            get {
                return ResourceManager.GetString("FileNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create folder. Please try again..
        /// </summary>
        public static string FolderCreateFailed {
            get {
                return ResourceManager.GetString("FolderCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder creation failed.
        /// </summary>
        public static string FolderCreateFailed_Title {
            get {
                return ResourceManager.GetString("FolderCreateFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have access to the path &apos;{0}&apos;. Please select another one and try again..
        /// </summary>
        public static string FolderUnauthorizedAccess {
            get {
                return ResourceManager.GetString("FolderUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string FolderUnauthorizedAccess_Title {
            get {
                return ResourceManager.GetString("FolderUnauthorizedAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve your account details. Please try again. [{0}].
        /// </summary>
        public static string GetAccountDetailsFailed {
            get {
                return ResourceManager.GetString("GetAccountDetailsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving account details failed.
        /// </summary>
        public static string GetAccountDetailsFailed_Title {
            get {
                return ResourceManager.GetString("GetAccountDetailsFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get link.
        /// </summary>
        public static string GetLinkFailed {
            get {
                return ResourceManager.GetString("GetLinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link creation failed.
        /// </summary>
        public static string GetLinkFailed_Title {
            get {
                return ResourceManager.GetString("GetLinkFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the available payment methods. Please try again. [{0}].
        /// </summary>
        public static string GetPaymentMethodsFailed {
            get {
                return ResourceManager.GetString("GetPaymentMethodsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting payment methods.
        /// </summary>
        public static string GetPaymentMethodsFailed_Title {
            get {
                return ResourceManager.GetString("GetPaymentMethodsFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the payment Url. Please try again. [{0}].
        /// </summary>
        public static string GetPaymentUrlFailed {
            get {
                return ResourceManager.GetString("GetPaymentUrlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving payment URL failed.
        /// </summary>
        public static string GetPaymentUrlFailed_Title {
            get {
                return ResourceManager.GetString("GetPaymentUrlFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve preview.
        /// </summary>
        public static string GetPreviewFailed {
            get {
                return ResourceManager.GetString("GetPreviewFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview failed.
        /// </summary>
        public static string GetPreviewFailed_Title {
            get {
                return ResourceManager.GetString("GetPreviewFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve thumbnail [{0}].
        /// </summary>
        public static string GetThumbnailFailed {
            get {
                return ResourceManager.GetString("GetThumbnailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting thumbnail failed.
        /// </summary>
        public static string GetThumbnailFailed_Title {
            get {
                return ResourceManager.GetString("GetThumbnailFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve your user data. Please try again. [{0}].
        /// </summary>
        public static string GetUserDataFailed {
            get {
                return ResourceManager.GetString("GetUserDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving user data failed.
        /// </summary>
        public static string GetUserDataFailed_Title {
            get {
                return ResourceManager.GetString("GetUserDataFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image successfully exported to &apos;saved pictures&apos; album.
        /// </summary>
        public static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved.
        /// </summary>
        public static string ImageSaved_Title {
            get {
                return ResourceManager.GetString("ImageSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting image to  &apos;saved pictures&apos; album. Please try again.
        /// </summary>
        public static string ImageSaveError {
            get {
                return ResourceManager.GetString("ImageSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save image.
        /// </summary>
        public static string ImageSaveError_Title {
            get {
                return ResourceManager.GetString("ImageSaveError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File import failed.
        /// </summary>
        public static string ImportFileFailed_Title {
            get {
                return ResourceManager.GetString("ImportFileFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file &apos;{0}&apos; is not valid or has illegal characters. Please change it and try again..
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name.
        /// </summary>
        public static string InvalidFileName_Title {
            get {
                return ResourceManager.GetString("InvalidFileName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name or path of the folder &apos;{0}&apos; is not valid or has illegal characters. Please change it and try again..
        /// </summary>
        public static string InvalidFolderNameOrPath {
            get {
                return ResourceManager.GetString("InvalidFolderNameOrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name or path.
        /// </summary>
        public static string InvalidFolderNameOrPath_Title {
            get {
                return ResourceManager.GetString("InvalidFolderNameOrPath_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact invitation could not be sent. Please try again..
        /// </summary>
        public static string InviteContactAddFailed {
            get {
                return ResourceManager.GetString("InviteContactAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to invite the contact.
        /// </summary>
        public static string InviteContactAddFailed_Title {
            get {
                return ResourceManager.GetString("InviteContactAddFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to add your own email as a contact..
        /// </summary>
        public static string InviteContactAddFailedOwnEmail {
            get {
                return ResourceManager.GetString("InviteContactAddFailedOwnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has been invited and will appear on your contact list once they have accepted the invitation..
        /// </summary>
        public static string InviteContactAddSuccessfully {
            get {
                return ResourceManager.GetString("InviteContactAddSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact invited.
        /// </summary>
        public static string InviteContactAddSuccessfully_Title {
            get {
                return ResourceManager.GetString("InviteContactAddSuccessfully_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MEGA link was copied to your clipboard.
        /// </summary>
        public static string LinkCopiedToClipboard {
            get {
                return ResourceManager.GetString("LinkCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        public static string LinkCopiedToClipboard_Title {
            get {
                return ResourceManager.GetString("LinkCopiedToClipboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load files and folders from MEGA. Please try again or click on refresh..
        /// </summary>
        public static string LoadNodesFailed {
            get {
                return ResourceManager.GetString("LoadNodesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load.
        /// </summary>
        public static string LoadNodesFailed_Title {
            get {
                return ResourceManager.GetString("LoadNodesFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged out.
        /// </summary>
        public static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out.
        /// </summary>
        public static string LoggedOut_Title {
            get {
                return ResourceManager.GetString("LoggedOut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA Cloud Drive login failed. Please try again. [{0}].
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LoginFailed_Title {
            get {
                return ResourceManager.GetString("LoginFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to logout. Please try again. [{0}].
        /// </summary>
        public static string LogoutFailed {
            get {
                return ResourceManager.GetString("LogoutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout failed.
        /// </summary>
        public static string LogoutFailed_Title {
            get {
                return ResourceManager.GetString("LogoutFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed e-mail. Please try again..
        /// </summary>
        public static string MalformedEmail {
            get {
                return ResourceManager.GetString("MalformedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free memory space to complete this operation. The app will shut down now.
        /// </summary>
        public static string MemoryLimitError {
            get {
                return ResourceManager.GetString("MemoryLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Limit.
        /// </summary>
        public static string MemoryLimitError_Title {
            get {
                return ResourceManager.GetString("MemoryLimitError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one picture for upload.
        /// </summary>
        public static string MinimalPictureSelection {
            get {
                return ResourceManager.GetString("MinimalPictureSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pictures selected.
        /// </summary>
        public static string MinimalPictureSelection_Title {
            get {
                return ResourceManager.GetString("MinimalPictureSelection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder is the same as the source folder. Move cancelled..
        /// </summary>
        public static string MoveEqualsParent {
            get {
                return ResourceManager.GetString("MoveEqualsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move failed.
        /// </summary>
        public static string MoveEqualsParent_Title {
            get {
                return ResourceManager.GetString("MoveEqualsParent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move item. Please try again..
        /// </summary>
        public static string MoveFailed {
            get {
                return ResourceManager.GetString("MoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move failed.
        /// </summary>
        public static string MoveFailed_Title {
            get {
                return ResourceManager.GetString("MoveFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move item to rubbish bin. Please try again.
        /// </summary>
        public static string MoveToRubbishBinFailed {
            get {
                return ResourceManager.GetString("MoveToRubbishBinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to rubbish bin failed.
        /// </summary>
        public static string MoveToRubbishBinFailed_Title {
            get {
                return ResourceManager.GetString("MoveToRubbishBinFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move {0} to the rubbish bin?.
        /// </summary>
        public static string MoveToRubbishBinQuestion {
            get {
                return ResourceManager.GetString("MoveToRubbishBinQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to rubbish bin?.
        /// </summary>
        public static string MoveToRubbishBinQuestion_Title {
            get {
                return ResourceManager.GetString("MoveToRubbishBinQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully moved to the rubbish bin.
        /// </summary>
        public static string MoveToRubbishBinSuccess {
            get {
                return ResourceManager.GetString("MoveToRubbishBinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item moved.
        /// </summary>
        public static string MoveToRubbishBinSuccess_Title {
            get {
                return ResourceManager.GetString("MoveToRubbishBinSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move {0} items to the rubbish bin?.
        /// </summary>
        public static string MultiMoveToRubbishBinQuestion {
            get {
                return ResourceManager.GetString("MultiMoveToRubbishBinQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move items?.
        /// </summary>
        public static string MultiMoveToRubbishBinQuestion_Title {
            get {
                return ResourceManager.GetString("MultiMoveToRubbishBinQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items moved to the rubbish bin.
        /// </summary>
        public static string MultiMoveToRubbishBinSucces {
            get {
                return ResourceManager.GetString("MultiMoveToRubbishBinSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items moved.
        /// </summary>
        public static string MultiMoveToRubbishBinSucces_Title {
            get {
                return ResourceManager.GetString("MultiMoveToRubbishBinSucces_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items removed.
        /// </summary>
        public static string MultiRemoveSucces {
            get {
                return ResourceManager.GetString("MultiRemoveSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items removed.
        /// </summary>
        public static string MultiRemoveSucces_Title {
            get {
                return ResourceManager.GetString("MultiRemoveSucces_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0} items?.
        /// </summary>
        public static string MultiSelectRemoveQuestion {
            get {
                return ResourceManager.GetString("MultiSelectRemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove items?.
        /// </summary>
        public static string MultiSelectRemoveQuestion_Title {
            get {
                return ResourceManager.GetString("MultiSelectRemoveQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new and the old password must not match..
        /// </summary>
        public static string NewAndOldPasswordMatch {
            get {
                return ResourceManager.GetString("NewAndOldPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected a default download location for your files.To proceed with the download, please select a destination folder or go to preferences in order to set up your default download location..
        /// </summary>
        public static string NoDownloadLocationSelected {
            get {
                return ResourceManager.GetString("NoDownloadLocationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot perform this action. Please connect to the Internet and try again..
        /// </summary>
        public static string NoInternetConnectionMessage {
            get {
                return ResourceManager.GetString("NoInternetConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the selected file.
        /// </summary>
        public static string OpenFileFailed {
            get {
                return ResourceManager.GetString("OpenFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File failed to open.
        /// </summary>
        public static string OpenFileFailed_Title {
            get {
                return ResourceManager.GetString("OpenFileFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not allowed, you will exceed the storage limit of your account. Do you want to upgrade your account?.
        /// </summary>
        public static string OverquotaAlert {
            get {
                return ResourceManager.GetString("OverquotaAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overquota Alert!.
        /// </summary>
        public static string OverquotaAlert_Title {
            get {
                return ResourceManager.GetString("OverquotaAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match. Please try again..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the file/folder &apos;{0}&apos; is too long. Please change it and try again..
        /// </summary>
        public static string PathTooLong {
            get {
                return ResourceManager.GetString("PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path too long.
        /// </summary>
        public static string PathTooLong_Title {
            get {
                return ResourceManager.GetString("PathTooLong_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to pause transfers.
        /// </summary>
        public static string PausingTransfersFailed {
            get {
                return ResourceManager.GetString("PausingTransfersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause failed.
        /// </summary>
        public static string PausingTransfersFailed_Title {
            get {
                return ResourceManager.GetString("PausingTransfersFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} pending transfers. Pending transfers will be canceled. Are you sure you want to exit?.
        /// </summary>
        public static string PendingTransfersExit {
            get {
                return ResourceManager.GetString("PendingTransfersExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Transfers.
        /// </summary>
        public static string PendingTransfersExit_Title {
            get {
                return ResourceManager.GetString("PendingTransfersExit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} pending transfers. Pending transfers will be canceled. Are you sure you want to logout?.
        /// </summary>
        public static string PendingTransfersLogout {
            get {
                return ResourceManager.GetString("PendingTransfersLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Transfers.
        /// </summary>
        public static string PendingTransfersLogout_Title {
            get {
                return ResourceManager.GetString("PendingTransfersLogout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload photo.
        /// </summary>
        public static string PhotoUploadError {
            get {
                return ResourceManager.GetString("PhotoUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo upload failed.
        /// </summary>
        public static string PhotoUploadError_Title {
            get {
                return ResourceManager.GetString("PhotoUploadError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image was saved to your photo album.
        /// </summary>
        public static string PictureSaved {
            get {
                return ResourceManager.GetString("PictureSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture saved.
        /// </summary>
        public static string PictureSaved_Title {
            get {
                return ResourceManager.GetString("PictureSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PIN lock codes do not match. Please re-type them and make sure they are equal.
        /// </summary>
        public static string PinLockCodesDoNotMatch {
            get {
                return ResourceManager.GetString("PinLockCodesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN lock codes do not match.
        /// </summary>
        public static string PinLockCodesDoNotMatch_Title {
            get {
                return ResourceManager.GetString("PinLockCodesDoNotMatch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN lock must be at least four digits.
        /// </summary>
        public static string PinLockTooShort {
            get {
                return ResourceManager.GetString("PinLockTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN lock too short.
        /// </summary>
        public static string PinLockTooShort_Title {
            get {
                return ResourceManager.GetString("PinLockTooShort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to prepare file: {0} for upload.
        /// </summary>
        public static string PrepareFileForUploadFailed {
            get {
                return ResourceManager.GetString("PrepareFileForUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error preparing file.
        /// </summary>
        public static string PrepareFileForUploadFailed_Title {
            get {
                return ResourceManager.GetString("PrepareFileForUploadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to prepare image: {0} for upload.
        /// </summary>
        public static string PrepareImageForUploadFailed {
            get {
                return ResourceManager.GetString("PrepareImageForUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing image failed.
        /// </summary>
        public static string PrepareImageForUploadFailed_Title {
            get {
                return ResourceManager.GetString("PrepareImageForUploadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your MEGA subcription purchase has failed or has been cancelled. Please try again or contact Windows Store support..
        /// </summary>
        public static string PurchaseFailed {
            get {
                return ResourceManager.GetString("PurchaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase failed or cancelled.
        /// </summary>
        public static string PurchaseFailed_Title {
            get {
                return ResourceManager.GetString("PurchaseFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your MEGA subcription purchase has succeeded..
        /// </summary>
        public static string PurchaseSucceeded {
            get {
                return ResourceManager.GetString("PurchaseSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase succeeded.
        /// </summary>
        public static string PurchaseSucceeded_Title {
            get {
                return ResourceManager.GetString("PurchaseSucceeded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your MEGA subcription purchase has not passed validation at our license server. On restart of this app we will retry to validate your subscription licenses. Please contact MEGA support if error continues..
        /// </summary>
        public static string PurchaseValidationFailed {
            get {
                return ResourceManager.GetString("PurchaseValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase validation failed.
        /// </summary>
        public static string PurchaseValidationFailed_Title {
            get {
                return ResourceManager.GetString("PurchaseValidationFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to automatically export image files to your photo album after download? You can change this setting on the settings page afterwards. Other file types will only be stored in the local storage of the app..
        /// </summary>
        public static string QuestionAskedDownloadOption {
            get {
                return ResourceManager.GetString("QuestionAskedDownloadOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no, only local.
        /// </summary>
        public static string QuestionAskedDownloadOption_NoButton {
            get {
                return ResourceManager.GetString("QuestionAskedDownloadOption_NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download options.
        /// </summary>
        public static string QuestionAskedDownloadOption_Title {
            get {
                return ResourceManager.GetString("QuestionAskedDownloadOption_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes, export.
        /// </summary>
        public static string QuestionAskedDownloadOption_YesButton {
            get {
                return ResourceManager.GetString("QuestionAskedDownloadOption_YesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0}?.
        /// </summary>
        public static string RemoveItemQuestion {
            get {
                return ResourceManager.GetString("RemoveItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove?.
        /// </summary>
        public static string RemoveItemQuestion_Title {
            get {
                return ResourceManager.GetString("RemoveItemQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove link. Please try again..
        /// </summary>
        public static string RemoveLinkFailed {
            get {
                return ResourceManager.GetString("RemoveLinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove item.
        /// </summary>
        public static string RemoveNodeFailed {
            get {
                return ResourceManager.GetString("RemoveNodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove failed.
        /// </summary>
        public static string RemoveNodeFailed_Title {
            get {
                return ResourceManager.GetString("RemoveNodeFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully removed.
        /// </summary>
        public static string RemoveNodeSuccess {
            get {
                return ResourceManager.GetString("RemoveNodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item removed.
        /// </summary>
        public static string RemoveNodeSuccess_Title {
            get {
                return ResourceManager.GetString("RemoveNodeSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming item failed.
        /// </summary>
        public static string RenameNodeFailed {
            get {
                return ResourceManager.GetString("RenameNodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename failed.
        /// </summary>
        public static string RenameNodeFailed_Title {
            get {
                return ResourceManager.GetString("RenameNodeFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in required fields.
        /// </summary>
        public static string RequiredFields_Title {
            get {
                return ResourceManager.GetString("RequiredFields_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give us your feedback. Thanks..
        /// </summary>
        public static string RequiredFieldsCancelSubscription {
            get {
                return ResourceManager.GetString("RequiredFieldsCancelSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your old MEGA password and your new MEGA password..
        /// </summary>
        public static string RequiredFieldsChangePassword {
            get {
                return ResourceManager.GetString("RequiredFieldsChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your chosen password..
        /// </summary>
        public static string RequiredFieldsConfirmAccount {
            get {
                return ResourceManager.GetString("RequiredFieldsConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your name, e-mail address and password.
        /// </summary>
        public static string RequiredFieldsCreateAccount {
            get {
                return ResourceManager.GetString("RequiredFieldsCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all the required fields and try again..
        /// </summary>
        public static string RequiredFieldsCreditCardPayment {
            get {
                return ResourceManager.GetString("RequiredFieldsCreditCardPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your e-mail address and your MEGA password..
        /// </summary>
        public static string RequiredFieldsLogin {
            get {
                return ResourceManager.GetString("RequiredFieldsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA automatic camera uploads.
        /// </summary>
        public static string ResourceIntensiveTaskDescription {
            get {
                return ResourceManager.GetString("ResourceIntensiveTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resume transfers.
        /// </summary>
        public static string ResumingTransfersFailed {
            get {
                return ResourceManager.GetString("ResumingTransfersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume failed.
        /// </summary>
        public static string ResumingTransfersFailed_Title {
            get {
                return ResourceManager.GetString("ResumingTransfersFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export current image to &apos;saved pictures&apos; album?.
        /// </summary>
        public static string SaveImageQuestion {
            get {
                return ResourceManager.GetString("SaveImageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image to photos.
        /// </summary>
        public static string SaveImageQuestion_Title {
            get {
                return ResourceManager.GetString("SaveImageQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save settings. Please, try again [{0}].
        /// </summary>
        public static string SaveSettingsFailed {
            get {
                return ResourceManager.GetString("SaveSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings.
        /// </summary>
        public static string SaveSettingsFailed_Title {
            get {
                return ResourceManager.GetString("SaveSettingsFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to select file(s). Please, try again [{0}].
        /// </summary>
        public static string SelectFileFailed {
            get {
                return ResourceManager.GetString("SelectFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File selection failed.
        /// </summary>
        public static string SelectFileFailed_Title {
            get {
                return ResourceManager.GetString("SelectFileFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to select folder. Please, try again or select another folder: [{0}].
        /// </summary>
        public static string SelectFolderFailed {
            get {
                return ResourceManager.GetString("SelectFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder failed.
        /// </summary>
        public static string SelectFolderFailed_Title {
            get {
                return ResourceManager.GetString("SelectFolderFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to select the folder. Please try again or select another folder..
        /// </summary>
        public static string SelectFolderFailedNoErrorCode {
            get {
                return ResourceManager.GetString("SelectFolderFailedNoErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out on this device from another location.
        /// </summary>
        public static string SessionIDError {
            get {
                return ResourceManager.GetString("SessionIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out.
        /// </summary>
        public static string SessionIDError_Title {
            get {
                return ResourceManager.GetString("SessionIDError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to open a shortcut. Maybe it is an invalid shortcut or the destination folder was deleted..
        /// </summary>
        public static string ShortCutFailed {
            get {
                return ResourceManager.GetString("ShortCutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut error.
        /// </summary>
        public static string ShortCutFailed_Title {
            get {
                return ResourceManager.GetString("ShortCutFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our SSL/TLS certificate can&apos;t be verified. You could be affected by a man-in-the-middle attack..
        /// </summary>
        public static string SSLKeyError {
            get {
                return ResourceManager.GetString("SSLKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out.
        /// </summary>
        public static string SSLKeyError_Title {
            get {
                return ResourceManager.GetString("SSLKeyError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation failed. Your credit card has not been charged..
        /// </summary>
        public static string UpgradeAccountFailed {
            get {
                return ResourceManager.GetString("UpgradeAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error upgrading account.
        /// </summary>
        public static string UpgradeAccountFailed_Title {
            get {
                return ResourceManager.GetString("UpgradeAccountFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully upgraded!.
        /// </summary>
        public static string UpgradeAccountSuccessfully {
            get {
                return ResourceManager.GetString("UpgradeAccountSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account upgraded.
        /// </summary>
        public static string UpgradeAccountSuccessfully_Title {
            get {
                return ResourceManager.GetString("UpgradeAccountSuccessfully_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload file. Please try again. [{0}].
        /// </summary>
        public static string UploadNodeFailed {
            get {
                return ResourceManager.GetString("UploadNodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed.
        /// </summary>
        public static string UploadNodeFailed_Title {
            get {
                return ResourceManager.GetString("UploadNodeFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload the selfie picture.
        /// </summary>
        public static string UploadSelfieFailed {
            get {
                return ResourceManager.GetString("UploadSelfieFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selfie upload failed.
        /// </summary>
        public static string UploadSelfieFailed_Title {
            get {
                return ResourceManager.GetString("UploadSelfieFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged into MEGA. Please re-login..
        /// </summary>
        public static string UserNotOnline {
            get {
                return ResourceManager.GetString("UserNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not online.
        /// </summary>
        public static string UserNotOnline_Title {
            get {
                return ResourceManager.GetString("UserNotOnline_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong data format.
        /// </summary>
        public static string WrongDataFormat_Title {
            get {
                return ResourceManager.GetString("WrongDataFormat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit card number, month/year of expiration and the CVV should be numeric. Please check that everything is correct and try again..
        /// </summary>
        public static string WrongDataFormatCreditCardPayment {
            get {
                return ResourceManager.GetString("WrongDataFormatCreditCardPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect e-mail address or password. Please try again..
        /// </summary>
        public static string WrongEmailPasswordLogin {
            get {
                return ResourceManager.GetString("WrongEmailPasswordLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The typed password is incorrect.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string WrongPassword_Title {
            get {
                return ResourceManager.GetString("WrongPassword_Title", resourceCulture);
            }
        }
    }
}
