//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MegaApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FREE.
        /// </summary>
        public static string AccountTypeFree {
            get {
                return ResourceManager.GetString("AccountTypeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LITE.
        /// </summary>
        public static string AccountTypeLite {
            get {
                return ResourceManager.GetString("AccountTypeLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRO I.
        /// </summary>
        public static string AccountTypePro1 {
            get {
                return ResourceManager.GetString("AccountTypePro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRO II.
        /// </summary>
        public static string AccountTypePro2 {
            get {
                return ResourceManager.GetString("AccountTypePro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRO III.
        /// </summary>
        public static string AccountTypePro3 {
            get {
                return ResourceManager.GetString("AccountTypePro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Z5dGhQhL.
        /// </summary>
        public static string AppKey {
            get {
                return ResourceManager.GetString("AppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA Privacy.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://g.api.mega.co.nz/.
        /// </summary>
        public static string AR_ApiUrl {
            get {
                return ResourceManager.GetString("AR_ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://mega.nz/copyright.
        /// </summary>
        public static string AR_CopyrightUrl {
            get {
                return ResourceManager.GetString("AR_CopyrightUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://mega.nz/gdpr.
        /// </summary>
        public static string AR_DataProtectionRegulationUrl {
            get {
                return ResourceManager.GetString("AR_DataProtectionRegulationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://mega.nz/general.
        /// </summary>
        public static string AR_GeneralLegalUrl {
            get {
                return ResourceManager.GetString("AR_GeneralLegalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://mega.nz.
        /// </summary>
        public static string AR_MegaUrl {
            get {
                return ResourceManager.GetString("AR_MegaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://mega.nz/privacy.
        /// </summary>
        public static string AR_PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("AR_PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGARecoveryKey.txt.
        /// </summary>
        public static string AR_RecoveryKeyFileName {
            get {
                return ResourceManager.GetString("AR_RecoveryKeyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://mega.nz/recovery.
        /// </summary>
        public static string AR_RecoveryUrl {
            get {
                return ResourceManager.GetString("AR_RecoveryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://github.com/meganz/sdk/tree/25559c2670a36547efd14fc24aafd62be266d7d3.
        /// </summary>
        public static string AR_SdkLink {
            get {
                return ResourceManager.GetString("AR_SdkLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 25559c2.
        /// </summary>
        public static string AR_SdkVersion {
            get {
                return ResourceManager.GetString("AR_SdkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://staging.api.mega.co.nz/.
        /// </summary>
        public static string AR_StagingUrl {
            get {
                return ResourceManager.GetString("AR_StagingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://mega.nz/takedown.
        /// </summary>
        public static string AR_TakedownGuidanceUrl {
            get {
                return ResourceManager.GetString("AR_TakedownGuidanceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://mega.nz/terms.
        /// </summary>
        public static string AR_TermsOfServiceUrl {
            get {
                return ResourceManager.GetString("AR_TermsOfServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a windowsphone@mega.nz.
        /// </summary>
        public static string DiagnosticsEmailAddress {
            get {
                return ResourceManager.GetString("DiagnosticsEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a downloads\.
        /// </summary>
        public static string DownloadsDirectory {
            get {
                return ResourceManager.GetString("DownloadsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.goedware.com.
        /// </summary>
        public static string GoedWareUrl {
            get {
                return ResourceManager.GetString("GoedWareUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA_WP.log.
        /// </summary>
        public static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Views/.
        /// </summary>
        public static string PagesLocation {
            get {
                return ResourceManager.GetString("PagesLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a previews\.
        /// </summary>
        public static string PreviewsDirectory {
            get {
                return ResourceManager.GetString("PreviewsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mega.microsoftstore.pro1.oneMonth.
        /// </summary>
        public static string Pro1Month {
            get {
                return ResourceManager.GetString("Pro1Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mega.microsoftstore.pro1.oneYear.
        /// </summary>
        public static string Pro1Year {
            get {
                return ResourceManager.GetString("Pro1Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mega.microsoftstore.pro2.oneMonth.
        /// </summary>
        public static string Pro2Month {
            get {
                return ResourceManager.GetString("Pro2Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mega.microsoftstore.pro2.oneYear.
        /// </summary>
        public static string Pro2Year {
            get {
                return ResourceManager.GetString("Pro2Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mega.microsoftstore.pro3.oneMonth.
        /// </summary>
        public static string Pro3Month {
            get {
                return ResourceManager.GetString("Pro3Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mega.microsoftstore.pro3.oneYear.
        /// </summary>
        public static string Pro3Year {
            get {
                return ResourceManager.GetString("Pro3Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mega.microsoftstore.prolite.oneMonth.
        /// </summary>
        public static string ProLiteMonth {
            get {
                return ResourceManager.GetString("ProLiteMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mega.microsoftstore.prolite.oneYear.
        /// </summary>
        public static string ProLiteYear {
            get {
                return ResourceManager.GetString("ProLiteYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 64.
        /// </summary>
        public static string ThumbnailHeight {
            get {
                return ResourceManager.GetString("ThumbnailHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a thumbnails\.
        /// </summary>
        public static string ThumbnailsDirectory {
            get {
                return ResourceManager.GetString("ThumbnailsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 64.
        /// </summary>
        public static string ThumbnailWidth {
            get {
                return ResourceManager.GetString("ThumbnailWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uploads\.
        /// </summary>
        public static string UploadsDirectory {
            get {
                return ResourceManager.GetString("UploadsDirectory", resourceCulture);
            }
        }
    }
}
