//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MegaApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z5dGhQhL.
        /// </summary>
        public static string AppKey {
            get {
                return ResourceManager.GetString("AppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA Privacy.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to windowsphone@mega.nz.
        /// </summary>
        public static string DiagnosticsEmailAddress {
            get {
                return ResourceManager.GetString("DiagnosticsEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads\.
        /// </summary>
        public static string DownloadsDirectory {
            get {
                return ResourceManager.GetString("DownloadsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.goedware.com.
        /// </summary>
        public static string GoedWareUrl {
            get {
                return ResourceManager.GetString("GoedWareUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA_WP.log.
        /// </summary>
        public static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/meganz/sdk.
        /// </summary>
        public static string MegaSdkUrl {
            get {
                return ResourceManager.GetString("MegaSdkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Pages/.
        /// </summary>
        public static string PagesLocation {
            get {
                return ResourceManager.GetString("PagesLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previews\.
        /// </summary>
        public static string PreviewsDirectory {
            get {
                return ResourceManager.GetString("PreviewsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mega.nz/mobile_privacy.html.
        /// </summary>
        public static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega.microsoftstore.pro1.oneMonth.
        /// </summary>
        public static string Pro1Month {
            get {
                return ResourceManager.GetString("Pro1Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega.microsoftstore.pro1.oneYear.
        /// </summary>
        public static string Pro1Year {
            get {
                return ResourceManager.GetString("Pro1Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega.microsoftstore.pro2.oneMonth.
        /// </summary>
        public static string Pro2Month {
            get {
                return ResourceManager.GetString("Pro2Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega.microsoftstore.pro2.oneYear.
        /// </summary>
        public static string Pro2Year {
            get {
                return ResourceManager.GetString("Pro2Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega.microsoftstore.pro3.oneMonth.
        /// </summary>
        public static string Pro3Month {
            get {
                return ResourceManager.GetString("Pro3Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega.microsoftstore.pro3.oneYear.
        /// </summary>
        public static string Pro3Year {
            get {
                return ResourceManager.GetString("Pro3Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega.microsoftstore.prolite.oneMonth.
        /// </summary>
        public static string ProLiteMonth {
            get {
                return ResourceManager.GetString("ProLiteMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega.microsoftstore.prolite.oneYear.
        /// </summary>
        public static string ProLiteYear {
            get {
                return ResourceManager.GetString("ProLiteYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mega.nz/mobile_terms.html.
        /// </summary>
        public static string TermsOfServiceUrl {
            get {
                return ResourceManager.GetString("TermsOfServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64.
        /// </summary>
        public static string ThumbnailHeight {
            get {
                return ResourceManager.GetString("ThumbnailHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thumbnails\.
        /// </summary>
        public static string ThumbnailsDirectory {
            get {
                return ResourceManager.GetString("ThumbnailsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64.
        /// </summary>
        public static string ThumbnailWidth {
            get {
                return ResourceManager.GetString("ThumbnailWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploads\.
        /// </summary>
        public static string UploadsDirectory {
            get {
                return ResourceManager.GetString("UploadsDirectory", resourceCulture);
            }
        }
    }
}
