//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProgressMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgressMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MegaApp.Resources.ProgressMessages", typeof(ProgressMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceling subscription....
        /// </summary>
        public static string CancelSubscription {
            get {
                return ResourceManager.GetString("CancelSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirming account....
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creating account....
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creating folder....
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Storing credit card....
        /// </summary>
        public static string CreditCardStore {
            get {
                return ResourceManager.GetString("CreditCardStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleting &apos;{0}&apos;....
        /// </summary>
        public static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retrieving download link....
        /// </summary>
        public static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resuming session....
        /// </summary>
        public static string FastLogin {
            get {
                return ResourceManager.GetString("FastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fetching files and folders... [{0}].
        /// </summary>
        public static string FetchingNodes {
            get {
                return ResourceManager.GetString("FetchingNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting account details....
        /// </summary>
        public static string GetAccountDetails {
            get {
                return ResourceManager.GetString("GetAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting contact data....
        /// </summary>
        public static string GetContactData {
            get {
                return ResourceManager.GetString("GetContactData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting link....
        /// </summary>
        public static string GetLink {
            get {
                return ResourceManager.GetString("GetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting payment methods....
        /// </summary>
        public static string GetPaymentMethods {
            get {
                return ResourceManager.GetString("GetPaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting payment Url....
        /// </summary>
        public static string GetPaymentUrl {
            get {
                return ResourceManager.GetString("GetPaymentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting preview....
        /// </summary>
        public static string GetPreview {
            get {
                return ResourceManager.GetString("GetPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting user data....
        /// </summary>
        public static string GetUserData {
            get {
                return ResourceManager.GetString("GetUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importing file....
        /// </summary>
        public static string ImportFile {
            get {
                return ResourceManager.GetString("ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Building view....
        /// </summary>
        public static string LoadNodes {
            get {
                return ResourceManager.GetString("LoadNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logging in....
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logging out....
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moving....
        /// </summary>
        public static string MoveNode {
            get {
                return ResourceManager.GetString("MoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moving to rubbish bin....
        /// </summary>
        public static string NodeToTrash {
            get {
                return ResourceManager.GetString("NodeToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pausing transfers....
        /// </summary>
        public static string PauseTransfers {
            get {
                return ResourceManager.GetString("PauseTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preparing downloads....
        /// </summary>
        public static string PrepareDownloads {
            get {
                return ResourceManager.GetString("PrepareDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preparing uploads....
        /// </summary>
        public static string PrepareUploads {
            get {
                return ResourceManager.GetString("PrepareUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removing....
        /// </summary>
        public static string RemoveNode {
            get {
                return ResourceManager.GetString("RemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renaming....
        /// </summary>
        public static string RenameNode {
            get {
                return ResourceManager.GetString("RenameNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resuming transfers....
        /// </summary>
        public static string ResumeTransfers {
            get {
                return ResourceManager.GetString("ResumeTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upgrading account....
        /// </summary>
        public static string UpgradeAccount {
            get {
                return ResourceManager.GetString("UpgradeAccount", resourceCulture);
            }
        }
    }
}
