//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProgressMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgressMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MegaApp.Resources.ProgressMessages", typeof(ProgressMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling transfer....
        /// </summary>
        public static string CancelTransfer {
            get {
                return ResourceManager.GetString("CancelTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing the rubbish bin....
        /// </summary>
        public static string CleanRubbishBin {
            get {
                return ResourceManager.GetString("CleanRubbishBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing credit card....
        /// </summary>
        public static string CreditCardStore {
            get {
                return ResourceManager.GetString("CreditCardStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting &apos;{0}&apos;....
        /// </summary>
        public static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving download link....
        /// </summary>
        public static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming session....
        /// </summary>
        public static string FastLogin {
            get {
                return ResourceManager.GetString("FastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching files and folders... [{0}].
        /// </summary>
        public static string FetchingNodes {
            get {
                return ResourceManager.GetString("FetchingNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting account details....
        /// </summary>
        public static string GetAccountDetails {
            get {
                return ResourceManager.GetString("GetAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting contact data....
        /// </summary>
        public static string GetContactData {
            get {
                return ResourceManager.GetString("GetContactData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting payment methods....
        /// </summary>
        public static string GetPaymentMethods {
            get {
                return ResourceManager.GetString("GetPaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting payment URL....
        /// </summary>
        public static string GetPaymentUrl {
            get {
                return ResourceManager.GetString("GetPaymentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting preview....
        /// </summary>
        public static string GetPreview {
            get {
                return ResourceManager.GetString("GetPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting user data....
        /// </summary>
        public static string GetUserData {
            get {
                return ResourceManager.GetString("GetUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing file....
        /// </summary>
        public static string ImportFile {
            get {
                return ResourceManager.GetString("ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending contact request....
        /// </summary>
        public static string InviteContactAdd {
            get {
                return ResourceManager.GetString("InviteContactAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting contact request....
        /// </summary>
        public static string InviteContactDelete {
            get {
                return ResourceManager.GetString("InviteContactDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminding contact about the request....
        /// </summary>
        public static string InviteContactRemind {
            get {
                return ResourceManager.GetString("InviteContactRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building view....
        /// </summary>
        public static string LoadNodes {
            get {
                return ResourceManager.GetString("LoadNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving....
        /// </summary>
        public static string MoveNode {
            get {
                return ResourceManager.GetString("MoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to Rubbish bin....
        /// </summary>
        public static string NodeToTrash {
            get {
                return ResourceManager.GetString("NodeToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing transfers....
        /// </summary>
        public static string PauseTransfers {
            get {
                return ResourceManager.GetString("PauseTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling subscription....
        /// </summary>
        public static string PM_CancelSubscription {
            get {
                return ResourceManager.GetString("PM_CancelSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing password....
        /// </summary>
        public static string PM_ChangePassword {
            get {
                return ResourceManager.GetString("PM_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing all sessions....
        /// </summary>
        public static string PM_CloseAllSessions {
            get {
                return ResourceManager.GetString("PM_CloseAllSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing session....
        /// </summary>
        public static string PM_CloseSession {
            get {
                return ResourceManager.GetString("PM_CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming account....
        /// </summary>
        public static string PM_ConfirmAccount {
            get {
                return ResourceManager.GetString("PM_ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying....
        /// </summary>
        public static string PM_CopyNode {
            get {
                return ResourceManager.GetString("PM_CopyNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating account....
        /// </summary>
        public static string PM_CreateAccount {
            get {
                return ResourceManager.GetString("PM_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating folder....
        /// </summary>
        public static string PM_CreateFolder {
            get {
                return ResourceManager.GetString("PM_CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting link....
        /// </summary>
        public static string PM_GetLink {
            get {
                return ResourceManager.GetString("PM_GetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importing folder....
        /// </summary>
        public static string PM_ImportFolder {
            get {
                return ResourceManager.GetString("PM_ImportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logging in....
        /// </summary>
        public static string PM_Login {
            get {
                return ResourceManager.GetString("PM_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out....
        /// </summary>
        public static string PM_Logout {
            get {
                return ResourceManager.GetString("PM_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening file link....
        /// </summary>
        public static string PM_OpenFileLink {
            get {
                return ResourceManager.GetString("PM_OpenFileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening folder link....
        /// </summary>
        public static string PM_OpenFolderLink {
            get {
                return ResourceManager.GetString("PM_OpenFolderLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing link....
        /// </summary>
        public static string PM_RemoveLink {
            get {
                return ResourceManager.GetString("PM_RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading account....
        /// </summary>
        public static string PM_UpgradeAccount {
            get {
                return ResourceManager.GetString("PM_UpgradeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing downloads....
        /// </summary>
        public static string PrepareDownloads {
            get {
                return ResourceManager.GetString("PrepareDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing uploads....
        /// </summary>
        public static string PrepareUploads {
            get {
                return ResourceManager.GetString("PrepareUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing contact....
        /// </summary>
        public static string RemoveContact {
            get {
                return ResourceManager.GetString("RemoveContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing from offline....
        /// </summary>
        public static string RemoveFromOffline {
            get {
                return ResourceManager.GetString("RemoveFromOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing....
        /// </summary>
        public static string RemoveNode {
            get {
                return ResourceManager.GetString("RemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming....
        /// </summary>
        public static string RenameNode {
            get {
                return ResourceManager.GetString("RenameNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting contact request....
        /// </summary>
        public static string ReplyContactRequestAccept {
            get {
                return ResourceManager.GetString("ReplyContactRequestAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denying contact request....
        /// </summary>
        public static string ReplyContactRequestDeny {
            get {
                return ResourceManager.GetString("ReplyContactRequestDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring contact request....
        /// </summary>
        public static string ReplyContactRequestIgnore {
            get {
                return ResourceManager.GetString("ReplyContactRequestIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming transfers....
        /// </summary>
        public static string ResumeTransfers {
            get {
                return ResourceManager.GetString("ResumeTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving for offline....
        /// </summary>
        public static string SaveForOffline {
            get {
                return ResourceManager.GetString("SaveForOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers too busy. Please wait….
        /// </summary>
        public static string ServersTooBusy {
            get {
                return ResourceManager.GetString("ServersTooBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating....
        /// </summary>
        public static string ValidatePurchase {
            get {
                return ResourceManager.GetString("ValidatePurchase", resourceCulture);
            }
        }
    }
}
