//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MegaApp.Resources.SettingsResources", typeof(SettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {72012C9A-F893-4CFF-9D42-944274C44935}.
        /// </summary>
        public static string AskDownloadLocationIsEnabled {
            get {
                return ResourceManager.GetString("AskDownloadLocationIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {7C0F8199-EFE6-4BA0-B982-93E6AB704A51}.
        /// </summary>
        public static string CameraUploadsConnectionType {
            get {
                return ResourceManager.GetString("CameraUploadsConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {09D0E27C-FF4C-4244-94C6-0797C341466A}.
        /// </summary>
        public static string CameraUploadsFileType {
            get {
                return ResourceManager.GetString("CameraUploadsFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {6F9C35B2-2139-48B6-908A-C4950A6BB624}.
        /// </summary>
        public static string CameraUploadsFirstInit {
            get {
                return ResourceManager.GetString("CameraUploadsFirstInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ED012CA3-EA51-45B0-BC66-3D585C612E74}.
        /// </summary>
        public static string CameraUploadsIsEnabled {
            get {
                return ResourceManager.GetString("CameraUploadsIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {46806F2D-6F8E-4A6F-851A-0F4BAABC2F7D}.
        /// </summary>
        public static string DebugModeIsEnabled {
            get {
                return ResourceManager.GetString("DebugModeIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {DA6C9F2D-6521-4BD5-BD5E-8F27C3F61E1A}.
        /// </summary>
        public static string DefaultDownloadLocation {
            get {
                return ResourceManager.GetString("DefaultDownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {AC2D08AF-7809-4FE9-8B3A-3582BCB24DC5}.
        /// </summary>
        public static string ExportImagesToPhotoAlbum {
            get {
                return ResourceManager.GetString("ExportImagesToPhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {13C908CC-E5A1-4D3F-80F2-D18BF2075619}.
        /// </summary>
        public static string LastAppVersion {
            get {
                return ResourceManager.GetString("LastAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {A8659687-3710-4B8D-8D0E-CAF3C3B44434}.
        /// </summary>
        public static string QuestionAskedDownloadOption {
            get {
                return ResourceManager.GetString("QuestionAskedDownloadOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {7C40A458-94B3-44D5-9FDB-DA6F73ADDE99}.
        /// </summary>
        public static string Receipts {
            get {
                return ResourceManager.GetString("Receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {92C84A5F-1387-4A44-AFE8-C44154B264D1}.
        /// </summary>
        public static string UserMegaEmailAddress {
            get {
                return ResourceManager.GetString("UserMegaEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {85DBF3E5-51E8-40BB-968C-8857B4FC6EF4}.
        /// </summary>
        public static string UserMegaSession {
            get {
                return ResourceManager.GetString("UserMegaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4405AB87-B1B8-4AE1-A59D-68DC036E569F}.
        /// </summary>
        public static string UserPinLock {
            get {
                return ResourceManager.GetString("UserPinLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {564DED0B-7DAA-47FA-A02A-4E00ED38749E}.
        /// </summary>
        public static string UserPinLockIsEnabled {
            get {
                return ResourceManager.GetString("UserPinLockIsEnabled", resourceCulture);
            }
        }
    }
}
