//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MegaApp.Resources.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have purchased a {0} account..
        /// </summary>
        public static string AccountPurchased {
            get {
                return ResourceManager.GetString("AccountPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} subscription will be automatically rebilled on your {0} anniversary unless you log in to your account and cancel this subscription payment prior to the renewal date..
        /// </summary>
        public static string AccountRenewalNotice {
            get {
                return ResourceManager.GetString("AccountRenewalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE.
        /// </summary>
        public static string AccountTypeFree {
            get {
                return ResourceManager.GetString("AccountTypeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LITE.
        /// </summary>
        public static string AccountTypeLite {
            get {
                return ResourceManager.GetString("AccountTypeLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO I.
        /// </summary>
        public static string AccountTypePro1 {
            get {
                return ResourceManager.GetString("AccountTypePro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO II.
        /// </summary>
        public static string AccountTypePro2 {
            get {
                return ResourceManager.GetString("AccountTypePro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO III.
        /// </summary>
        public static string AccountTypePro3 {
            get {
                return ResourceManager.GetString("AccountTypePro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgements.
        /// </summary>
        public static string Acknowledgements {
            get {
                return ResourceManager.GetString("Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add contact.
        /// </summary>
        public static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with the.
        /// </summary>
        public static string AgreeCreateAccount {
            get {
                return ResourceManager.GetString("AgreeCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual.
        /// </summary>
        public static string Annual {
            get {
                return ResourceManager.GetString("Annual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annually.
        /// </summary>
        public static string Annually {
            get {
                return ResourceManager.GetString("Annually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA Privacy.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version.
        /// </summary>
        public static string AppVersionText {
            get {
                return ResourceManager.GetString("AppVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always ask for download location.
        /// </summary>
        public static string AskDownloadLocationText {
            get {
                return ResourceManager.GetString("AskDownloadLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Upload.
        /// </summary>
        public static string AutoUpload {
            get {
                return ResourceManager.GetString("AutoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome!.
        /// </summary>
        public static string Awesome {
            get {
                return ResourceManager.GetString("Awesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth.
        /// </summary>
        public static string Bandwidth {
            get {
                return ResourceManager.GetString("Bandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing details.
        /// </summary>
        public static string BillingDetails {
            get {
                return ResourceManager.GetString("BillingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        public static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Uploads.
        /// </summary>
        public static string CameraUploads {
            get {
                return ResourceManager.GetString("CameraUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all.
        /// </summary>
        public static string CancelAll {
            get {
                return ResourceManager.GetString("CancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all transfers.
        /// </summary>
        public static string CancelAllTransfers {
            get {
                return ResourceManager.GetString("CancelAllTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel subscription.
        /// </summary>
        public static string CancelSubscription {
            get {
                return ResourceManager.GetString("CancelSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PIN Lock.
        /// </summary>
        public static string ChangePinLock {
            get {
                return ResourceManager.GetString("ChangePinLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose payment method.
        /// </summary>
        public static string ChoosePaymentMethod {
            get {
                return ResourceManager.GetString("ChoosePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose renewal period below.
        /// </summary>
        public static string ChooseRenewalPeriod {
            get {
                return ResourceManager.GetString("ChooseRenewalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up transfers.
        /// </summary>
        public static string CleanUpTransfers {
            get {
                return ResourceManager.GetString("CleanUpTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cache.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty rubbish.
        /// </summary>
        public static string ClearRubbishBin {
            get {
                return ResourceManager.GetString("ClearRubbishBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selection.
        /// </summary>
        public static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all sessions.
        /// </summary>
        public static string CloseAllSessions {
            get {
                return ResourceManager.GetString("CloseAllSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close session.
        /// </summary>
        public static string CloseSession {
            get {
                return ResourceManager.GetString("CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Drive.
        /// </summary>
        public static string CloudDriveName {
            get {
                return ResourceManager.GetString("CloudDriveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm account.
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        public static string ConfirmPasswordWatermark {
            get {
                return ResourceManager.GetString("ConfirmPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your PIN lock.
        /// </summary>
        public static string ConfirmPinLockWatermark {
            get {
                return ResourceManager.GetString("ConfirmPinLockWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type email address:.
        /// </summary>
        public static string CreateContact {
            get {
                return ResourceManager.GetString("CreateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name:.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shortcut.
        /// </summary>
        public static string CreateShortCut {
            get {
                return ResourceManager.GetString("CreateShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number.
        /// </summary>
        public static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card recurring payments.
        /// </summary>
        public static string CreditCardRecurringPayments {
            get {
                return ResourceManager.GetString("CreditCardRecurringPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        public static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default download location.
        /// </summary>
        public static string DefaultDownloadLocationText {
            get {
                return ResourceManager.GetString("DefaultDownloadLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        public static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download location.
        /// </summary>
        public static string DownloadLocation {
            get {
                return ResourceManager.GetString("DownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail address.
        /// </summary>
        public static string EmailWatermark {
            get {
                return ResourceManager.GetString("EmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty folder.
        /// </summary>
        public static string EmptyFolder {
            get {
                return ResourceManager.GetString("EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transfers.
        /// </summary>
        public static string EmptyTransfers {
            get {
                return ResourceManager.GetString("EmptyTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Camera Uploads.
        /// </summary>
        public static string EnableCameraUploads {
            get {
                return ResourceManager.GetString("EnableCameraUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your payment details below.
        /// </summary>
        public static string EnterPaymentDetails {
            get {
                return ResourceManager.GetString("EnterPaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires on.
        /// </summary>
        public static string ExpiresOn {
            get {
                return ResourceManager.GetString("ExpiresOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export MasterKey.
        /// </summary>
        public static string ExportMasterKeyText {
            get {
                return ResourceManager.GetString("ExportMasterKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export images to &apos;saved pictures&apos; album after download.
        /// </summary>
        public static string ExportPhotoAlbumText {
            get {
                return ResourceManager.GetString("ExportPhotoAlbumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files (ascending).
        /// </summary>
        public static string FilesAscendingSortOption {
            get {
                return ResourceManager.GetString("FilesAscendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files (descending).
        /// </summary>
        public static string FilesDescendingSortOption {
            get {
                return ResourceManager.GetString("FilesDescendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free space.
        /// </summary>
        public static string FreeSpace {
            get {
                return ResourceManager.GetString("FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get 2 months free if you subscribe to a one-year pro plan.
        /// </summary>
        public static string Get2MonthsFree {
            get {
                return ResourceManager.GetString("Get2MonthsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get link.
        /// </summary>
        public static string GetLink {
            get {
                return ResourceManager.GetString("GetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can be a PRO user!.
        /// </summary>
        public static string GetProAccount {
            get {
                return ResourceManager.GetString("GetProAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeRoot {
            get {
                return ResourceManager.GetString("HomeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored.
        /// </summary>
        public static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image upload.
        /// </summary>
        public static string ImageUpload {
            get {
                return ResourceManager.GetString("ImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to destination and import or download link.
        /// </summary>
        public static string ImportLinkBorderText {
            get {
                return ResourceManager.GetString("ImportLinkBorderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        public static string Incoming {
            get {
                return ResourceManager.GetString("Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA access.
        /// </summary>
        public static string InitTourAccess_Title {
            get {
                return ResourceManager.GetString("InitTourAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get.
        /// </summary>
        public static string InitTourAccess1 {
            get {
                return ResourceManager.GetString("InitTourAccess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fully encrypted access.
        /// </summary>
        public static string InitTourAccess2 {
            get {
                return ResourceManager.GetString("InitTourAccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anywhere, anytime..
        /// </summary>
        public static string InitTourAccess3 {
            get {
                return ResourceManager.GetString("InitTourAccess3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA privacy.
        /// </summary>
        public static string InitTourPrivacy_Title {
            get {
                return ResourceManager.GetString("InitTourPrivacy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keep your files safe with MEGA&apos;s.
        /// </summary>
        public static string InitTourPrivacy1 {
            get {
                return ResourceManager.GetString("InitTourPrivacy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end-to-end encryption..
        /// </summary>
        public static string InitTourPrivacy2 {
            get {
                return ResourceManager.GetString("InitTourPrivacy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA space.
        /// </summary>
        public static string InitTourSpace_Title {
            get {
                return ResourceManager.GetString("InitTourSpace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register now and get.
        /// </summary>
        public static string InitTourSpace1 {
            get {
                return ResourceManager.GetString("InitTourSpace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 GB of free space..
        /// </summary>
        public static string InitTourSpace2 {
            get {
                return ResourceManager.GetString("InitTourSpace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA speed.
        /// </summary>
        public static string InitTourSpeed_Title {
            get {
                return ResourceManager.GetString("InitTourSpeed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfers are fast..
        /// </summary>
        public static string InitTourSpeed1 {
            get {
                return ResourceManager.GetString("InitTourSpeed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quickly share files with everyone..
        /// </summary>
        public static string InitTourSpeed2 {
            get {
                return ResourceManager.GetString("InitTourSpeed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest.
        /// </summary>
        public static string LargestSortOption {
            get {
                return ResourceManager.GetString("LargestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited.
        /// </summary>
        public static string Limited {
            get {
                return ResourceManager.GetString("Limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link options.
        /// </summary>
        public static string LinkOptions {
            get {
                return ResourceManager.GetString("LinkOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading preview....
        /// </summary>
        public static string LoadingPreview {
            get {
                return ResourceManager.GetString("LoadingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a PIN Lock.
        /// </summary>
        public static string MakePinLock {
            get {
                return ResourceManager.GetString("MakePinLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage link.
        /// </summary>
        public static string ManageLink {
            get {
                return ResourceManager.GetString("ManageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterKey.
        /// </summary>
        public static string MasterKey {
            get {
                return ResourceManager.GetString("MasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA SDK.
        /// </summary>
        public static string MEGA_SDK {
            get {
                return ResourceManager.GetString("MEGA_SDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA contacts.
        /// </summary>
        public static string MEGAContacts {
            get {
                return ResourceManager.GetString("MEGAContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA link:.
        /// </summary>
        public static string MegaLinkTitle {
            get {
                return ResourceManager.GetString("MegaLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to share this MEGA cloud service file with you.
        /// </summary>
        public static string MegaShareLinkMessage {
            get {
                return ResourceManager.GetString("MegaShareLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string MultipleFiles {
            get {
                return ResourceManager.GetString("MultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string MultipleFolders {
            get {
                return ResourceManager.GetString("MultipleFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi select.
        /// </summary>
        public static string MultiSelect {
            get {
                return ResourceManager.GetString("MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (ascending).
        /// </summary>
        public static string NameAscendingSortOption {
            get {
                return ResourceManager.GetString("NameAscendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (descending).
        /// </summary>
        public static string NameDescendingSortOption {
            get {
                return ResourceManager.GetString("NameDescendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string NameWatermark {
            get {
                return ResourceManager.GetString("NameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string NewestSortOption {
            get {
                return ResourceManager.GetString("NewestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password.
        /// </summary>
        public static string NewPasswordWatermark {
            get {
                return ResourceManager.GetString("NewPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new PIN lock.
        /// </summary>
        public static string NewPinLockWatermark {
            get {
                return ResourceManager.GetString("NewPinLockWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to show.
        /// </summary>
        public static string NoDataToShow {
            get {
                return ResourceManager.GetString("NoDataToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this time, there is no payment method available for this plan.
        /// </summary>
        public static string NoPaymentMethodsAvailable {
            get {
                return ResourceManager.GetString("NoPaymentMethodsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plans to display.
        /// </summary>
        public static string NoPlansToDisplay {
            get {
                return ResourceManager.GetString("NoPlansToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transfers.
        /// </summary>
        public static string NoTransfers {
            get {
                return ResourceManager.GetString("NoTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string OldestSortOption {
            get {
                return ResourceManager.GetString("OldestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open link.
        /// </summary>
        public static string OpenLink {
            get {
                return ResourceManager.GetString("OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open MEGA download link:.
        /// </summary>
        public static string OpenLinkText {
            get {
                return ResourceManager.GetString("OpenLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional).
        /// </summary>
        public static string OptionalParenthesis {
            get {
                return ResourceManager.GetString("OptionalParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating system restrictions.
        /// </summary>
        public static string OSRestrictions {
            get {
                return ResourceManager.GetString("OSRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing.
        /// </summary>
        public static string Outgoing {
            get {
                return ResourceManager.GetString("Outgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        public static string PasswordWatermark {
            get {
                return ResourceManager.GetString("PasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste MEGA download link:.
        /// </summary>
        public static string PasteMegaDownloadLink {
            get {
                return ResourceManager.GetString("PasteMegaDownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause all.
        /// </summary>
        public static string PauseAll {
            get {
                return ResourceManager.GetString("PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment details.
        /// </summary>
        public static string PaymentDetails {
            get {
                return ResourceManager.GetString("PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string PhoneBill {
            get {
                return ResourceManager.GetString("PhoneBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos only.
        /// </summary>
        public static string PhotosOnly {
            get {
                return ResourceManager.GetString("PhotosOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Lock.
        /// </summary>
        public static string PinLock {
            get {
                return ResourceManager.GetString("PinLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PIN lock.
        /// </summary>
        public static string PinLockWatermark {
            get {
                return ResourceManager.GetString("PinLockWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External power source connected.
        /// </summary>
        public static string PowerConnected {
            get {
                return ResourceManager.GetString("PowerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctual.
        /// </summary>
        public static string Punctual {
            get {
                return ResourceManager.GetString("Punctual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received requests.
        /// </summary>
        public static string ReceivedRequests {
            get {
                return ResourceManager.GetString("ReceivedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        public static string Recurring {
            get {
                return ResourceManager.GetString("Recurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinvite.
        /// </summary>
        public static string Reinvite {
            get {
                return ResourceManager.GetString("Reinvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminded.
        /// </summary>
        public static string Reminded {
            get {
                return ResourceManager.GetString("Reminded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove link.
        /// </summary>
        public static string RemoveLink {
            get {
                return ResourceManager.GetString("RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a new name:.
        /// </summary>
        public static string RenameItem {
            get {
                return ResourceManager.GetString("RenameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renews on.
        /// </summary>
        public static string RenewsOn {
            get {
                return ResourceManager.GetString("RenewsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubbish bin.
        /// </summary>
        public static string RubbishBinName {
            get {
                return ResourceManager.GetString("RubbishBinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubbish bin.
        /// </summary>
        public static string RubbishBinRoot {
            get {
                return ResourceManager.GetString("RubbishBinRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected the {0} Plan.
        /// </summary>
        public static string SelectedPlan {
            get {
                return ResourceManager.GetString("SelectedPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select membership.
        /// </summary>
        public static string SelectMembership {
            get {
                return ResourceManager.GetString("SelectMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select photo.
        /// </summary>
        public static string SelectPhoto {
            get {
                return ResourceManager.GetString("SelectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selfie mode.
        /// </summary>
        public static string SelfieMode {
            get {
                return ResourceManager.GetString("SelfieMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send file.
        /// </summary>
        public static string SendFile {
            get {
                return ResourceManager.GetString("SendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent requests.
        /// </summary>
        public static string SentRequests {
            get {
                return ResourceManager.GetString("SentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsShort {
            get {
                return ResourceManager.GetString("SettingsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enable the Auto Camera Uploads service?.
        /// </summary>
        public static string SetupCameraUploadsQuestion {
            get {
                return ResourceManager.GetString("SetupCameraUploadsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up camera uploads.
        /// </summary>
        public static string SetupCameraUploadsTitle {
            get {
                return ResourceManager.GetString("SetupCameraUploadsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared folders.
        /// </summary>
        public static string SharedFolders {
            get {
                return ResourceManager.GetString("SharedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared items.
        /// </summary>
        public static string SharedItems {
            get {
                return ResourceManager.GetString("SharedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share folder.
        /// </summary>
        public static string ShareFolder {
            get {
                return ResourceManager.GetString("ShareFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share folders.
        /// </summary>
        public static string ShareFolders {
            get {
                return ResourceManager.GetString("ShareFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string SingleFile {
            get {
                return ResourceManager.GetString("SingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string SingleFolder {
            get {
                return ResourceManager.GetString("SingleFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smallest.
        /// </summary>
        public static string SmallestSortOption {
            get {
                return ResourceManager.GetString("SmallestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SortByMenuTitle {
            get {
                return ResourceManager.GetString("SortByMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to special thank the following companies/people for making this app possible:.
        /// </summary>
        public static string SpecialThankYou {
            get {
                return ResourceManager.GetString("SpecialThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/resume all.
        /// </summary>
        public static string StartResumeAll {
            get {
                return ResourceManager.GetString("StartResumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay logged in.
        /// </summary>
        public static string StayLoggedInText {
            get {
                return ResourceManager.GetString("StayLoggedInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string StorageShort {
            get {
                return ResourceManager.GetString("StorageShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo.
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string TimeDaysAgo {
            get {
                return ResourceManager.GetString("TimeDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string TimeHoursAgo {
            get {
                return ResourceManager.GetString("TimeHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string TimeMinutesAgo {
            get {
                return ResourceManager.GetString("TimeMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string TimeSecondsAgo {
            get {
                return ResourceManager.GetString("TimeSecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Transfer_Canceled {
            get {
                return ResourceManager.GetString("Transfer_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling.
        /// </summary>
        public static string Transfer_Canceling {
            get {
                return ResourceManager.GetString("Transfer_Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Transfer_Download {
            get {
                return ResourceManager.GetString("Transfer_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string Transfer_Downloaded {
            get {
                return ResourceManager.GetString("Transfer_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Transfer_Error {
            get {
                return ResourceManager.GetString("Transfer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string Transfer_NotStarted {
            get {
                return ResourceManager.GetString("Transfer_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Transfer_Paused {
            get {
                return ResourceManager.GetString("Transfer_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing.
        /// </summary>
        public static string Transfer_Pausing {
            get {
                return ResourceManager.GetString("Transfer_Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string Transfer_Queued {
            get {
                return ResourceManager.GetString("Transfer_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Transfer_Upload {
            get {
                return ResourceManager.GetString("Transfer_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string Transfer_Uploaded {
            get {
                return ResourceManager.GetString("Transfer_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        public static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade account.
        /// </summary>
        public static string UpgradeAccount {
            get {
                return ResourceManager.GetString("UpgradeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to upgrade your account?.
        /// </summary>
        public static string UpgradeAccountQuestion {
            get {
                return ResourceManager.GetString("UpgradeAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade now!.
        /// </summary>
        public static string UpgradeNow {
            get {
                return ResourceManager.GetString("UpgradeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload options.
        /// </summary>
        public static string UploadOptionsTitle {
            get {
                return ResourceManager.GetString("UploadOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads.
        /// </summary>
        public static string Uploads {
            get {
                return ResourceManager.GetString("Uploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload settings.
        /// </summary>
        public static string UploadSettings {
            get {
                return ResourceManager.GetString("UploadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used space.
        /// </summary>
        public static string UsedSpace {
            get {
                return ResourceManager.GetString("UsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re running out of space!.
        /// </summary>
        public static string WarningOutOfSpace {
            get {
                return ResourceManager.GetString("WarningOutOfSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi and Data plan.
        /// </summary>
        public static string WifiAndDataPlan {
            get {
                return ResourceManager.GetString("WifiAndDataPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-fi only.
        /// </summary>
        public static string WifiOnly {
            get {
                return ResourceManager.GetString("WifiOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
