//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MegaApp.Resources.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have purchased a {0} account..
        /// </summary>
        public static string AccountPurchased {
            get {
                return ResourceManager.GetString("AccountPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your {0} subscription will be automatically rebilled on your {0} anniversary unless you log in to your account and cancel the subscription prior to the renewal date..
        /// </summary>
        public static string AccountRenewalNotice {
            get {
                return ResourceManager.GetString("AccountRenewalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FREE.
        /// </summary>
        public static string AccountTypeFree {
            get {
                return ResourceManager.GetString("AccountTypeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LITE.
        /// </summary>
        public static string AccountTypeLite {
            get {
                return ResourceManager.GetString("AccountTypeLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRO I.
        /// </summary>
        public static string AccountTypePro1 {
            get {
                return ResourceManager.GetString("AccountTypePro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRO II.
        /// </summary>
        public static string AccountTypePro2 {
            get {
                return ResourceManager.GetString("AccountTypePro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRO III.
        /// </summary>
        public static string AccountTypePro3 {
            get {
                return ResourceManager.GetString("AccountTypePro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acknowledgements.
        /// </summary>
        public static string Acknowledgements {
            get {
                return ResourceManager.GetString("Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Contact.
        /// </summary>
        public static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I agree with the.
        /// </summary>
        public static string AgreeCreateAccount {
            get {
                return ResourceManager.GetString("AgreeCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Annual.
        /// </summary>
        public static string Annual {
            get {
                return ResourceManager.GetString("Annual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Annually.
        /// </summary>
        public static string Annually {
            get {
                return ResourceManager.GetString("Annually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA Privacy.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App version.
        /// </summary>
        public static string AppVersionText {
            get {
                return ResourceManager.GetString("AppVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Always ask for download location.
        /// </summary>
        public static string AskDownloadLocationText {
            get {
                return ResourceManager.GetString("AskDownloadLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto Upload.
        /// </summary>
        public static string AutoUpload {
            get {
                return ResourceManager.GetString("AutoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Awesome!.
        /// </summary>
        public static string Awesome {
            get {
                return ResourceManager.GetString("Awesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bandwidth.
        /// </summary>
        public static string Bandwidth {
            get {
                return ResourceManager.GetString("Bandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Billing details.
        /// </summary>
        public static string BillingDetails {
            get {
                return ResourceManager.GetString("BillingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cache.
        /// </summary>
        public static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camera Uploads.
        /// </summary>
        public static string CameraUploads {
            get {
                return ResourceManager.GetString("CameraUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancel all.
        /// </summary>
        public static string CancelAll {
            get {
                return ResourceManager.GetString("CancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel all transfers.
        /// </summary>
        public static string CancelAllTransfers {
            get {
                return ResourceManager.GetString("CancelAllTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a capture.
        /// </summary>
        public static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change PIN Lock.
        /// </summary>
        public static string ChangePinLock {
            get {
                return ResourceManager.GetString("ChangePinLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose payment method.
        /// </summary>
        public static string ChoosePaymentMethod {
            get {
                return ResourceManager.GetString("ChoosePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose renewal period below.
        /// </summary>
        public static string ChooseRenewalPeriod {
            get {
                return ResourceManager.GetString("ChooseRenewalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clean up transfers.
        /// </summary>
        public static string CleanUpTransfers {
            get {
                return ResourceManager.GetString("CleanUpTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clear cache.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty rubbish bin.
        /// </summary>
        public static string ClearRubbishBin {
            get {
                return ResourceManager.GetString("ClearRubbishBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clear selection.
        /// </summary>
        public static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clipboard.
        /// </summary>
        public static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cloud Drive.
        /// </summary>
        public static string CloudDriveName {
            get {
                return ResourceManager.GetString("CloudDriveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a confirm your password.
        /// </summary>
        public static string ConfirmPasswordWatermark {
            get {
                return ResourceManager.GetString("ConfirmPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a confirm your PIN lock.
        /// </summary>
        public static string ConfirmPinLockWatermark {
            get {
                return ResourceManager.GetString("ConfirmPinLockWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type e-mail address:.
        /// </summary>
        public static string CreateContact {
            get {
                return ResourceManager.GetString("CreateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create shortcut.
        /// </summary>
        public static string CreateShortCut {
            get {
                return ResourceManager.GetString("CreateShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credit card.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credit Card Number.
        /// </summary>
        public static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credit Card recurring payments.
        /// </summary>
        public static string CreditCardRecurringPayments {
            get {
                return ResourceManager.GetString("CreditCardRecurringPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CVV.
        /// </summary>
        public static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a default download folder..
        /// </summary>
        public static string DefaultDownloadLocation {
            get {
                return ResourceManager.GetString("DefaultDownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default download location.
        /// </summary>
        public static string DefaultDownloadLocationText {
            get {
                return ResourceManager.GetString("DefaultDownloadLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denied.
        /// </summary>
        public static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developer.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dismiss.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download location.
        /// </summary>
        public static string DownloadLocation {
            get {
                return ResourceManager.GetString("DownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your e-mail address.
        /// </summary>
        public static string EmailWatermark {
            get {
                return ResourceManager.GetString("EmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No files in your cloud drive.
        /// </summary>
        public static string EmptyCloudDrive {
            get {
                return ResourceManager.GetString("EmptyCloudDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a empty folder.
        /// </summary>
        public static string EmptyFolder {
            get {
                return ResourceManager.GetString("EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No items saved for offline.
        /// </summary>
        public static string EmptyOffline {
            get {
                return ResourceManager.GetString("EmptyOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty rubbish bin.
        /// </summary>
        public static string EmptyRubbishBin {
            get {
                return ResourceManager.GetString("EmptyRubbishBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No shared folders.
        /// </summary>
        public static string EmptySharedFolders {
            get {
                return ResourceManager.GetString("EmptySharedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No transfers.
        /// </summary>
        public static string EmptyTransfers {
            get {
                return ResourceManager.GetString("EmptyTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable Camera Uploads.
        /// </summary>
        public static string EnableCameraUploads {
            get {
                return ResourceManager.GetString("EnableCameraUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your payment details below.
        /// </summary>
        public static string EnterPaymentDetails {
            get {
                return ResourceManager.GetString("EnterPaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expires on.
        /// </summary>
        public static string ExpiresOn {
            get {
                return ResourceManager.GetString("ExpiresOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export masterkey.
        /// </summary>
        public static string ExportMasterKeyText {
            get {
                return ResourceManager.GetString("ExportMasterKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export images to &apos;saved pictures&apos; album after download.
        /// </summary>
        public static string ExportPhotoAlbumText {
            get {
                return ResourceManager.GetString("ExportPhotoAlbumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a files (ascending).
        /// </summary>
        public static string FilesAscendingSortOption {
            get {
                return ResourceManager.GetString("FilesAscendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a files (descending).
        /// </summary>
        public static string FilesDescendingSortOption {
            get {
                return ResourceManager.GetString("FilesDescendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File upload.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Free space.
        /// </summary>
        public static string FreeSpace {
            get {
                return ResourceManager.GetString("FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get 2 months free if you subscribe to a one-year Pro plan.
        /// </summary>
        public static string Get2MonthsFree {
            get {
                return ResourceManager.GetString("Get2MonthsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can be a Pro user!.
        /// </summary>
        public static string GetProAccount {
            get {
                return ResourceManager.GetString("GetProAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string HomeRoot {
            get {
                return ResourceManager.GetString("HomeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignored.
        /// </summary>
        public static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image upload.
        /// </summary>
        public static string ImageUpload {
            get {
                return ResourceManager.GetString("ImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browse to destination and import or download link.
        /// </summary>
        public static string ImportLinkBorderText {
            get {
                return ResourceManager.GetString("ImportLinkBorderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incoming.
        /// </summary>
        public static string Incoming {
            get {
                return ResourceManager.GetString("Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA access.
        /// </summary>
        public static string InitTourAccess_Title {
            get {
                return ResourceManager.GetString("InitTourAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get.
        /// </summary>
        public static string InitTourAccess1 {
            get {
                return ResourceManager.GetString("InitTourAccess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fully encrypted access.
        /// </summary>
        public static string InitTourAccess2 {
            get {
                return ResourceManager.GetString("InitTourAccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a anywhere, anytime..
        /// </summary>
        public static string InitTourAccess3 {
            get {
                return ResourceManager.GetString("InitTourAccess3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA privacy.
        /// </summary>
        public static string InitTourPrivacy_Title {
            get {
                return ResourceManager.GetString("InitTourPrivacy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a keep your files safe with MEGA&apos;s.
        /// </summary>
        public static string InitTourPrivacy1 {
            get {
                return ResourceManager.GetString("InitTourPrivacy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a end-to-end encryption..
        /// </summary>
        public static string InitTourPrivacy2 {
            get {
                return ResourceManager.GetString("InitTourPrivacy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA space.
        /// </summary>
        public static string InitTourSpace_Title {
            get {
                return ResourceManager.GetString("InitTourSpace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a register now and get.
        /// </summary>
        public static string InitTourSpace1 {
            get {
                return ResourceManager.GetString("InitTourSpace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 50 GB of free space..
        /// </summary>
        public static string InitTourSpace2 {
            get {
                return ResourceManager.GetString("InitTourSpace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA speed.
        /// </summary>
        public static string InitTourSpeed_Title {
            get {
                return ResourceManager.GetString("InitTourSpeed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a transfers are fast..
        /// </summary>
        public static string InitTourSpeed1 {
            get {
                return ResourceManager.GetString("InitTourSpeed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a quickly share files with everyone..
        /// </summary>
        public static string InitTourSpeed2 {
            get {
                return ResourceManager.GetString("InitTourSpeed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Largest.
        /// </summary>
        public static string LargestSortOption {
            get {
                return ResourceManager.GetString("LargestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limited.
        /// </summary>
        public static string Limited {
            get {
                return ResourceManager.GetString("Limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link options.
        /// </summary>
        public static string LinkOptions {
            get {
                return ResourceManager.GetString("LinkOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading preview....
        /// </summary>
        public static string LoadingPreview {
            get {
                return ResourceManager.GetString("LoadingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Make a PIN Lock.
        /// </summary>
        public static string MakePinLock {
            get {
                return ResourceManager.GetString("MakePinLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage link.
        /// </summary>
        public static string ManageLink {
            get {
                return ResourceManager.GetString("ManageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master Key.
        /// </summary>
        public static string MasterKey {
            get {
                return ResourceManager.GetString("MasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA SDK.
        /// </summary>
        public static string MEGA_SDK {
            get {
                return ResourceManager.GetString("MEGA_SDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA contacts.
        /// </summary>
        public static string MEGAContacts {
            get {
                return ResourceManager.GetString("MEGAContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA link:.
        /// </summary>
        public static string MegaLinkTitle {
            get {
                return ResourceManager.GetString("MegaLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I want to share this MEGA cloud service file with you.
        /// </summary>
        public static string MegaShareLinkMessage {
            get {
                return ResourceManager.GetString("MegaShareLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a files.
        /// </summary>
        public static string MultipleFiles {
            get {
                return ResourceManager.GetString("MultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a folders.
        /// </summary>
        public static string MultipleFolders {
            get {
                return ResourceManager.GetString("MultipleFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multi select.
        /// </summary>
        public static string MultiSelect {
            get {
                return ResourceManager.GetString("MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a my account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name (ascending).
        /// </summary>
        public static string NameAscendingSortOption {
            get {
                return ResourceManager.GetString("NameAscendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name (descending).
        /// </summary>
        public static string NameDescendingSortOption {
            get {
                return ResourceManager.GetString("NameDescendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Newest.
        /// </summary>
        public static string NewestSortOption {
            get {
                return ResourceManager.GetString("NewestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your new password.
        /// </summary>
        public static string NewPasswordWatermark {
            get {
                return ResourceManager.GetString("NewPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your new PIN lock.
        /// </summary>
        public static string NewPinLockWatermark {
            get {
                return ResourceManager.GetString("NewPinLockWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No data to show.
        /// </summary>
        public static string NoDataToShow {
            get {
                return ResourceManager.GetString("NoDataToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No downloads.
        /// </summary>
        public static string NoDownloads {
            get {
                return ResourceManager.GetString("NoDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No internet connection.
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a At this time, there is no payment method available for this plan.
        /// </summary>
        public static string NoPaymentMethodsAvailable {
            get {
                return ResourceManager.GetString("NoPaymentMethodsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No plans to display.
        /// </summary>
        public static string NoPlansToDisplay {
            get {
                return ResourceManager.GetString("NoPlansToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No transfers.
        /// </summary>
        public static string NoTransfers {
            get {
                return ResourceManager.GetString("NoTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No uploads.
        /// </summary>
        public static string NoUploads {
            get {
                return ResourceManager.GetString("NoUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oldest.
        /// </summary>
        public static string OldestSortOption {
            get {
                return ResourceManager.GetString("OldestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open MEGA download link:.
        /// </summary>
        public static string OpenLink {
            get {
                return ResourceManager.GetString("OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open MEGA download link:.
        /// </summary>
        public static string OpenLinkText {
            get {
                return ResourceManager.GetString("OpenLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Optional).
        /// </summary>
        public static string OptionalParenthesis {
            get {
                return ResourceManager.GetString("OptionalParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operating system restrictions.
        /// </summary>
        public static string OSRestrictions {
            get {
                return ResourceManager.GetString("OSRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outgoing.
        /// </summary>
        public static string Outgoing {
            get {
                return ResourceManager.GetString("Outgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your password.
        /// </summary>
        public static string PasswordWatermark {
            get {
                return ResourceManager.GetString("PasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste MEGA download link:.
        /// </summary>
        public static string PasteMegaDownloadLink {
            get {
                return ResourceManager.GetString("PasteMegaDownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pause all.
        /// </summary>
        public static string PauseAll {
            get {
                return ResourceManager.GetString("PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment details.
        /// </summary>
        public static string PaymentDetails {
            get {
                return ResourceManager.GetString("PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Bill.
        /// </summary>
        public static string PhoneBill {
            get {
                return ResourceManager.GetString("PhoneBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Photos only.
        /// </summary>
        public static string PhotosOnly {
            get {
                return ResourceManager.GetString("PhotosOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PIN Lock.
        /// </summary>
        public static string PinLock {
            get {
                return ResourceManager.GetString("PinLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your PIN lock.
        /// </summary>
        public static string PinLockWatermark {
            get {
                return ResourceManager.GetString("PinLockWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a External power source connected.
        /// </summary>
        public static string PowerConnected {
            get {
                return ResourceManager.GetString("PowerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punctual.
        /// </summary>
        public static string Punctual {
            get {
                return ResourceManager.GetString("Punctual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Received requests.
        /// </summary>
        public static string ReceivedRequests {
            get {
                return ResourceManager.GetString("ReceivedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recurring.
        /// </summary>
        public static string Recurring {
            get {
                return ResourceManager.GetString("Recurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reinvite.
        /// </summary>
        public static string Reinvite {
            get {
                return ResourceManager.GetString("Reinvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reminded.
        /// </summary>
        public static string Reminded {
            get {
                return ResourceManager.GetString("Reminded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type a new name:.
        /// </summary>
        public static string RenameItem {
            get {
                return ResourceManager.GetString("RenameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renews on.
        /// </summary>
        public static string RenewsOn {
            get {
                return ResourceManager.GetString("RenewsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rubbish bin.
        /// </summary>
        public static string RubbishBinName {
            get {
                return ResourceManager.GetString("RubbishBinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rubbish Bin.
        /// </summary>
        public static string RubbishBinRoot {
            get {
                return ResourceManager.GetString("RubbishBinRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved for offline use.
        /// </summary>
        public static string SavedForOffline {
            get {
                return ResourceManager.GetString("SavedForOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have selected the {0} Plan.
        /// </summary>
        public static string SelectedPlan {
            get {
                return ResourceManager.GetString("SelectedPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select membership.
        /// </summary>
        public static string SelectMembership {
            get {
                return ResourceManager.GetString("SelectMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select photo.
        /// </summary>
        public static string SelectPhoto {
            get {
                return ResourceManager.GetString("SelectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selfie mode.
        /// </summary>
        public static string SelfieMode {
            get {
                return ResourceManager.GetString("SelfieMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send file.
        /// </summary>
        public static string SendFile {
            get {
                return ResourceManager.GetString("SendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sent requests.
        /// </summary>
        public static string SentRequests {
            get {
                return ResourceManager.GetString("SentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string SettingsShort {
            get {
                return ResourceManager.GetString("SettingsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to enable the Auto Camera Uploads service?.
        /// </summary>
        public static string SetupCameraUploadsQuestion {
            get {
                return ResourceManager.GetString("SetupCameraUploadsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set up camera uploads.
        /// </summary>
        public static string SetupCameraUploadsTitle {
            get {
                return ResourceManager.GetString("SetupCameraUploadsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shared folders.
        /// </summary>
        public static string SharedFolders {
            get {
                return ResourceManager.GetString("SharedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shared items.
        /// </summary>
        public static string SharedItems {
            get {
                return ResourceManager.GetString("SharedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Share folder.
        /// </summary>
        public static string ShareFolder {
            get {
                return ResourceManager.GetString("ShareFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Share folders.
        /// </summary>
        public static string ShareFolders {
            get {
                return ResourceManager.GetString("ShareFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a file.
        /// </summary>
        public static string SingleFile {
            get {
                return ResourceManager.GetString("SingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a folder.
        /// </summary>
        public static string SingleFolder {
            get {
                return ResourceManager.GetString("SingleFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size:.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Smallest.
        /// </summary>
        public static string SmallestSortOption {
            get {
                return ResourceManager.GetString("SmallestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sort by.
        /// </summary>
        public static string SortByMenuTitle {
            get {
                return ResourceManager.GetString("SortByMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We want to special thank the following companies/people for making this app possible:.
        /// </summary>
        public static string SpecialThankYou {
            get {
                return ResourceManager.GetString("SpecialThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a start/resume all.
        /// </summary>
        public static string StartResumeAll {
            get {
                return ResourceManager.GetString("StartResumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stay logged in.
        /// </summary>
        public static string StayLoggedInText {
            get {
                return ResourceManager.GetString("StayLoggedInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Storage.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Storage.
        /// </summary>
        public static string StorageShort {
            get {
                return ResourceManager.GetString("StorageShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take photo.
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terms of service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} days ago.
        /// </summary>
        public static string TimeDaysAgo {
            get {
                return ResourceManager.GetString("TimeDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} hours ago.
        /// </summary>
        public static string TimeHoursAgo {
            get {
                return ResourceManager.GetString("TimeHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} minutes ago.
        /// </summary>
        public static string TimeMinutesAgo {
            get {
                return ResourceManager.GetString("TimeMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} seconds ago.
        /// </summary>
        public static string TimeSecondsAgo {
            get {
                return ResourceManager.GetString("TimeSecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceled.
        /// </summary>
        public static string Transfer_Canceled {
            get {
                return ResourceManager.GetString("Transfer_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceling....
        /// </summary>
        public static string Transfer_Canceling {
            get {
                return ResourceManager.GetString("Transfer_Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading....
        /// </summary>
        public static string Transfer_Download {
            get {
                return ResourceManager.GetString("Transfer_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloaded.
        /// </summary>
        public static string Transfer_Downloaded {
            get {
                return ResourceManager.GetString("Transfer_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error on transfer.
        /// </summary>
        public static string Transfer_Error {
            get {
                return ResourceManager.GetString("Transfer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        public static string Transfer_NotStarted {
            get {
                return ResourceManager.GetString("Transfer_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paused.
        /// </summary>
        public static string Transfer_Paused {
            get {
                return ResourceManager.GetString("Transfer_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pausing....
        /// </summary>
        public static string Transfer_Pausing {
            get {
                return ResourceManager.GetString("Transfer_Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Queued.
        /// </summary>
        public static string Transfer_Queued {
            get {
                return ResourceManager.GetString("Transfer_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uploading....
        /// </summary>
        public static string Transfer_Upload {
            get {
                return ResourceManager.GetString("Transfer_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uploaded.
        /// </summary>
        public static string Transfer_Uploaded {
            get {
                return ResourceManager.GetString("Transfer_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a transfers.
        /// </summary>
        public static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel subscription.
        /// </summary>
        public static string UI_CancelSubscription {
            get {
                return ResourceManager.GetString("UI_CancelSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string UI_ChangePassword {
            get {
                return ResourceManager.GetString("UI_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close all sessions.
        /// </summary>
        public static string UI_CloseAllSessions {
            get {
                return ResourceManager.GetString("UI_CloseAllSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close session.
        /// </summary>
        public static string UI_CloseSession {
            get {
                return ResourceManager.GetString("UI_CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm account.
        /// </summary>
        public static string UI_ConfirmAccount {
            get {
                return ResourceManager.GetString("UI_ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create account.
        /// </summary>
        public static string UI_CreateAccount {
            get {
                return ResourceManager.GetString("UI_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folder name:.
        /// </summary>
        public static string UI_CreateFolder {
            get {
                return ResourceManager.GetString("UI_CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your first name.
        /// </summary>
        public static string UI_FirstNameWatermark {
            get {
                return ResourceManager.GetString("UI_FirstNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get link.
        /// </summary>
        public static string UI_GetLink {
            get {
                return ResourceManager.GetString("UI_GetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your last name.
        /// </summary>
        public static string UI_LastNameWatermark {
            get {
                return ResourceManager.GetString("UI_LastNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string UI_Login {
            get {
                return ResourceManager.GetString("UI_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string UI_Logout {
            get {
                return ResourceManager.GetString("UI_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove link.
        /// </summary>
        public static string UI_RemoveLink {
            get {
                return ResourceManager.GetString("UI_RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upgrade account.
        /// </summary>
        public static string UI_UpgradeAccount {
            get {
                return ResourceManager.GetString("UI_UpgradeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to upgrade your account?.
        /// </summary>
        public static string UpgradeAccountQuestion {
            get {
                return ResourceManager.GetString("UpgradeAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upgrade now!.
        /// </summary>
        public static string UpgradeNow {
            get {
                return ResourceManager.GetString("UpgradeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload options.
        /// </summary>
        public static string UploadOptionsTitle {
            get {
                return ResourceManager.GetString("UploadOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uploads.
        /// </summary>
        public static string Uploads {
            get {
                return ResourceManager.GetString("Uploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload settings.
        /// </summary>
        public static string UploadSettings {
            get {
                return ResourceManager.GetString("UploadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Used Space.
        /// </summary>
        public static string UsedSpace {
            get {
                return ResourceManager.GetString("UsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a view.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;re running out of space!.
        /// </summary>
        public static string WarningOutOfSpace {
            get {
                return ResourceManager.GetString("WarningOutOfSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wifi and Data plan.
        /// </summary>
        public static string WifiAndDataPlan {
            get {
                return ResourceManager.GetString("WifiAndDataPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wifi only.
        /// </summary>
        public static string WifiOnly {
            get {
                return ResourceManager.GetString("WifiOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
