//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MegaApp.Resources.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FREE.
        /// </summary>
        public static string AccountTypeFree {
            get {
                return ResourceManager.GetString("AccountTypeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRO I.
        /// </summary>
        public static string AccountTypePro1 {
            get {
                return ResourceManager.GetString("AccountTypePro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRO II.
        /// </summary>
        public static string AccountTypePro2 {
            get {
                return ResourceManager.GetString("AccountTypePro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRO III.
        /// </summary>
        public static string AccountTypePro3 {
            get {
                return ResourceManager.GetString("AccountTypePro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRO Lite.
        /// </summary>
        public static string AccountTypeProLite {
            get {
                return ResourceManager.GetString("AccountTypeProLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acknowledgements.
        /// </summary>
        public static string Acknowledgements {
            get {
                return ResourceManager.GetString("Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a acknowledgements.
        /// </summary>
        public static string AcknowledgementsTitle {
            get {
                return ResourceManager.GetString("AcknowledgementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I agree with the.
        /// </summary>
        public static string AgreeCreateAccount {
            get {
                return ResourceManager.GetString("AgreeCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Annually.
        /// </summary>
        public static string Annually {
            get {
                return ResourceManager.GetString("Annually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App version.
        /// </summary>
        public static string AppVersionText {
            get {
                return ResourceManager.GetString("AppVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Always ask for download location.
        /// </summary>
        public static string AskDownloadLocationText {
            get {
                return ResourceManager.GetString("AskDownloadLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bandwidth.
        /// </summary>
        public static string Bandwidth {
            get {
                return ResourceManager.GetString("Bandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cache.
        /// </summary>
        public static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancel all.
        /// </summary>
        public static string CancelAll {
            get {
                return ResourceManager.GetString("CancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a capture.
        /// </summary>
        public static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change PIN Lock.
        /// </summary>
        public static string ChangePinLock {
            get {
                return ResourceManager.GetString("ChangePinLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change PIN Lock.
        /// </summary>
        public static string ChangePinLockButton {
            get {
                return ResourceManager.GetString("ChangePinLockButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clean up transfers.
        /// </summary>
        public static string CleanUpTransfers {
            get {
                return ResourceManager.GetString("CleanUpTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clear cache.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clear selection.
        /// </summary>
        public static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clipboard.
        /// </summary>
        public static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cloud Drive.
        /// </summary>
        public static string CloudDriveName {
            get {
                return ResourceManager.GetString("CloudDriveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a confirm account.
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a confirm your password.
        /// </summary>
        public static string ConfirmPasswordWatermark {
            get {
                return ResourceManager.GetString("ConfirmPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a confirm your PIN lock.
        /// </summary>
        public static string ConfirmPinLockWatermark {
            get {
                return ResourceManager.GetString("ConfirmPinLockWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a copy.
        /// </summary>
        public static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a create account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a registration.
        /// </summary>
        public static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Created:.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folder name:.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new account here.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create shortcut.
        /// </summary>
        public static string CreateShortCut {
            get {
                return ResourceManager.GetString("CreateShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your current PIN lock.
        /// </summary>
        public static string CurrentPinLockWatermark {
            get {
                return ResourceManager.GetString("CurrentPinLockWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default download location.
        /// </summary>
        public static string DefaultDownloadLocationText {
            get {
                return ResourceManager.GetString("DefaultDownloadLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a done.
        /// </summary>
        public static string DoneButton {
            get {
                return ResourceManager.GetString("DoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download location.
        /// </summary>
        public static string DownloadLocation {
            get {
                return ResourceManager.GetString("DownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading....
        /// </summary>
        public static string DownloadNode {
            get {
                return ResourceManager.GetString("DownloadNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your e-mail address.
        /// </summary>
        public static string EmailWatermark {
            get {
                return ResourceManager.GetString("EmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a empty folder.
        /// </summary>
        public static string EmptyFolder {
            get {
                return ResourceManager.GetString("EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No transfers.
        /// </summary>
        public static string EmptyTransfers {
            get {
                return ResourceManager.GetString("EmptyTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export masterkey.
        /// </summary>
        public static string ExportMasterKeyText {
            get {
                return ResourceManager.GetString("ExportMasterKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export images to &apos;saved pictures&apos; album after download.
        /// </summary>
        public static string ExportPhotoAlbumText {
            get {
                return ResourceManager.GetString("ExportPhotoAlbumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a files (ascending).
        /// </summary>
        public static string FilesAscendingSortOption {
            get {
                return ResourceManager.GetString("FilesAscendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a files (descending).
        /// </summary>
        public static string FilesDescendingSortOption {
            get {
                return ResourceManager.GetString("FilesDescendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File upload.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Free space.
        /// </summary>
        public static string FreeSpace {
            get {
                return ResourceManager.GetString("FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get link.
        /// </summary>
        public static string GetPreviewLink {
            get {
                return ResourceManager.GetString("GetPreviewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string HomeRoot {
            get {
                return ResourceManager.GetString("HomeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image upload.
        /// </summary>
        public static string ImageUpload {
            get {
                return ResourceManager.GetString("ImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inbox.
        /// </summary>
        public static string InboxName {
            get {
                return ResourceManager.GetString("InboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a largest.
        /// </summary>
        public static string LargestSortOption {
            get {
                return ResourceManager.GetString("LargestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link options.
        /// </summary>
        public static string LinkOptions {
            get {
                return ResourceManager.GetString("LinkOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading preview....
        /// </summary>
        public static string LoadingPreview {
            get {
                return ResourceManager.GetString("LoadingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a login.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Make a PIN Lock.
        /// </summary>
        public static string MakePinLock {
            get {
                return ResourceManager.GetString("MakePinLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MasterKey.
        /// </summary>
        public static string MasterKey {
            get {
                return ResourceManager.GetString("MasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA SDK.
        /// </summary>
        public static string MEGA_SDK {
            get {
                return ResourceManager.GetString("MEGA_SDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA link:.
        /// </summary>
        public static string MegaLinkTitle {
            get {
                return ResourceManager.GetString("MegaLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I want to share this MEGA cloud service file with you.
        /// </summary>
        public static string MegaShareLinkMessage {
            get {
                return ResourceManager.GetString("MegaShareLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a files.
        /// </summary>
        public static string MultipleFiles {
            get {
                return ResourceManager.GetString("MultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a folders.
        /// </summary>
        public static string MultipleFolders {
            get {
                return ResourceManager.GetString("MultipleFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multi select.
        /// </summary>
        public static string MultiSelect {
            get {
                return ResourceManager.GetString("MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a my account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a name (ascending).
        /// </summary>
        public static string NameAscendingSortOption {
            get {
                return ResourceManager.GetString("NameAscendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a name (descending).
        /// </summary>
        public static string NameDescendingSortOption {
            get {
                return ResourceManager.GetString("NameDescendingSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your name.
        /// </summary>
        public static string NameWatermark {
            get {
                return ResourceManager.GetString("NameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New at MEGA? .
        /// </summary>
        public static string NewAtMega {
            get {
                return ResourceManager.GetString("NewAtMega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a newest.
        /// </summary>
        public static string NewestSortOption {
            get {
                return ResourceManager.GetString("NewestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your new PIN lock.
        /// </summary>
        public static string NewPinLockWatermark {
            get {
                return ResourceManager.GetString("NewPinLockWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No data to show.
        /// </summary>
        public static string NoDataToShow {
            get {
                return ResourceManager.GetString("NoDataToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No plans to display.
        /// </summary>
        public static string NoPlansToDisplay {
            get {
                return ResourceManager.GetString("NoPlansToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No transfers.
        /// </summary>
        public static string NoTransfers {
            get {
                return ResourceManager.GetString("NoTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a oldest.
        /// </summary>
        public static string OldestSortOption {
            get {
                return ResourceManager.GetString("OldestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a open.
        /// </summary>
        public static string OpenButton {
            get {
                return ResourceManager.GetString("OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open MEGA download link:.
        /// </summary>
        public static string OpenLink {
            get {
                return ResourceManager.GetString("OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a open link.
        /// </summary>
        public static string OpenLinkAppBar {
            get {
                return ResourceManager.GetString("OpenLinkAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your password.
        /// </summary>
        public static string PasswordWatermark {
            get {
                return ResourceManager.GetString("PasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pause all.
        /// </summary>
        public static string PauseAll {
            get {
                return ResourceManager.GetString("PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PIN Lock.
        /// </summary>
        public static string PinLock {
            get {
                return ResourceManager.GetString("PinLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your PIN lock.
        /// </summary>
        public static string PinLockWatermark {
            get {
                return ResourceManager.GetString("PinLockWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rename.
        /// </summary>
        public static string RenameButton {
            get {
                return ResourceManager.GetString("RenameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type a new name:.
        /// </summary>
        public static string RenameItem {
            get {
                return ResourceManager.GetString("RenameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rubbish Bin.
        /// </summary>
        public static string RubbishBin {
            get {
                return ResourceManager.GetString("RubbishBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rubbish Bin.
        /// </summary>
        public static string RubbishBinRoot {
            get {
                return ResourceManager.GetString("RubbishBinRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select photo.
        /// </summary>
        public static string SelectPhoto {
            get {
                return ResourceManager.GetString("SelectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selfie mode.
        /// </summary>
        public static string SelfieMode {
            get {
                return ResourceManager.GetString("SelfieMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a share.
        /// </summary>
        public static string ShareButton {
            get {
                return ResourceManager.GetString("ShareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a file.
        /// </summary>
        public static string SingleFile {
            get {
                return ResourceManager.GetString("SingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a folder.
        /// </summary>
        public static string SingleFolder {
            get {
                return ResourceManager.GetString("SingleFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size:.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a smallest.
        /// </summary>
        public static string SmallestSortOption {
            get {
                return ResourceManager.GetString("SmallestSortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SORT BY.
        /// </summary>
        public static string SortByMenuTitle {
            get {
                return ResourceManager.GetString("SortByMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We want to special thank the following companies/people for making this app possible:.
        /// </summary>
        public static string SpecialThankYou {
            get {
                return ResourceManager.GetString("SpecialThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a start/resume all.
        /// </summary>
        public static string StartResumeAll {
            get {
                return ResourceManager.GetString("StartResumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stay logged in.
        /// </summary>
        public static string StayLoggedInText {
            get {
                return ResourceManager.GetString("StayLoggedInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Storage.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Storage.
        /// </summary>
        public static string StorageSubscriptionPlans {
            get {
                return ResourceManager.GetString("StorageSubscriptionPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take photo.
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terms of service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a terms of use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceled.
        /// </summary>
        public static string Transfer_Canceled {
            get {
                return ResourceManager.GetString("Transfer_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceling....
        /// </summary>
        public static string Transfer_Canceling {
            get {
                return ResourceManager.GetString("Transfer_Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connecting server....
        /// </summary>
        public static string Transfer_Connecting {
            get {
                return ResourceManager.GetString("Transfer_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading....
        /// </summary>
        public static string Transfer_Download {
            get {
                return ResourceManager.GetString("Transfer_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error on transfer.
        /// </summary>
        public static string Transfer_Error {
            get {
                return ResourceManager.GetString("Transfer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finished.
        /// </summary>
        public static string Transfer_Finished {
            get {
                return ResourceManager.GetString("Transfer_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        public static string Transfer_NotStarted {
            get {
                return ResourceManager.GetString("Transfer_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paused.
        /// </summary>
        public static string Transfer_Paused {
            get {
                return ResourceManager.GetString("Transfer_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pausing....
        /// </summary>
        public static string Transfer_Pausing {
            get {
                return ResourceManager.GetString("Transfer_Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uploading....
        /// </summary>
        public static string Transfer_Upload {
            get {
                return ResourceManager.GetString("Transfer_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a transfers.
        /// </summary>
        public static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rubbish Bin.
        /// </summary>
        public static string TrashBinName {
            get {
                return ResourceManager.GetString("TrashBinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uploading....
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload options.
        /// </summary>
        public static string UploadOptionsTitle {
            get {
                return ResourceManager.GetString("UploadOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uploads.
        /// </summary>
        public static string Uploads {
            get {
                return ResourceManager.GetString("Uploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Used space.
        /// </summary>
        public static string UsedSpace {
            get {
                return ResourceManager.GetString("UsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a view.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        public static string ViewOrginal {
            get {
                return ResourceManager.GetString("ViewOrginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
