//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VisualResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisualResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MegaApp.Resources.VisualResources", typeof(VisualResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 0.000,0.000 L 0.000,14.000 L 8.000,7.000 L 0.000,0.000 Z.
        /// </summary>
        public static string BreadCrumbArrowData {
            get {
                return ResourceManager.GetString("BreadCrumbArrowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 43.000,30.000 C 43.000,31.654 41.654,33.000 40.000,33.000 L 6.000,33.000 C 4.346,33.000 3.000,31.654 3.000,30.000 L 3.000,27.879 L 13.500,17.379 L 19.500,23.379 L 33.750,9.129 L 43.000,18.000 L 43.000,30.000 Z M 19.000,6.000 C 21.206,6.000 23.000,7.794 23.000,10.000 C 23.000,12.206 21.206,14.000 19.000,14.000 C 16.794,14.000 15.000,12.206 15.000,10.000 C 15.000,7.794 16.794,6.000 19.000,6.000 Z M 40.000,0.000 L 6.000,0.000 C 2.692,0.000 0.000,2.692 0.000,6.000 L 0.000,30.000 C 0.000,33.308 2.692,36.000 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CameraUploadsPathData {
            get {
                return ResourceManager.GetString("CameraUploadsPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 0.000,23.266 C 0.000,29.191 4.430,34.000 9.872,34.000 L 38.128,34.000 C 43.570,34.000 48.000,29.191 48.000,23.266 C 48.000,17.518 43.826,12.807 38.592,12.548 L 38.592,12.515 C 38.592,5.618 33.440,0.000 27.072,0.000 C 22.944,0.000 19.328,2.348 17.296,5.877 C 16.608,5.553 15.856,5.359 15.072,5.359 C 11.954,5.359 9.408,8.128 9.408,11.495 C 9.408,11.868 9.440,12.208 9.488,12.548 C 4.208,12.758 0.000,17.470 0.000,23.266.
        /// </summary>
        public static string CloudDriveMenuPathData {
            get {
                return ResourceManager.GetString("CloudDriveMenuPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 32.370,26.550 C 31.544,25.665 23.985,22.140 22.575,21.660 C 22.575,21.360 22.425,20.280 22.020,20.100 C 21.630,19.950 20.385,19.335 20.385,19.335 C 20.385,19.245 20.235,18.975 20.222,18.690 C 20.222,18.375 20.385,18.075 20.385,18.075 C 20.550,17.745 21.163,16.950 21.331,16.335 C 21.495,15.720 21.690,14.145 21.690,14.145 C 21.690,13.815 22.185,13.665 22.485,13.500 C 23.025,13.245 23.475,9.885 23.475,9.885 C 23.475,8.790 23.025,9.255 23.025,8.475 L 23.025,5.550 C 23.025,1.950 19.995,0.000 16.425,0.000 L  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContactsPathData {
            get {
                return ResourceManager.GetString("ContactsPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 20.000,0.958 L 20.000,4.630 C 20.000,5.644 19.579,6.617 18.828,7.336 L 10.000,16.000 L 1.172,7.336 C 0.421,6.617 0.000,5.644 0.000,4.630 L 0.000,0.958 C 0.000,0.106 1.077,-0.320 1.707,0.282 L 10.000,8.000 L 18.293,0.282 C 18.923,-0.320 20.000,0.106 20.000,0.958 Z.
        /// </summary>
        public static string GoToBottomPathData {
            get {
                return ResourceManager.GetString("GoToBottomPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 0.000,15.042 L 0.000,11.370 C -0.000,10.356 0.421,9.383 1.172,8.664 L 10.000,0.000 L 18.828,8.664 C 19.579,9.383 20.000,10.356 20.000,11.370 L 20.000,15.042 C 20.000,15.894 18.923,16.320 18.293,15.718 L 10.000,8.000 L 1.707,15.718 C 1.077,16.320 0.000,15.894 0.000,15.042 Z.
        /// </summary>
        public static string GoToTopPathData {
            get {
                return ResourceManager.GetString("GoToTopPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 1.000,0.000 L 23.000,0.000 C 23.552,0.000 24.000,0.448 24.000,1.000 L 24.000,3.000 C 24.000,3.552 23.552,4.000 23.000,4.000 L 1.000,4.000 C 0.448,4.000 0.000,3.552 0.000,3.000 L 0.000,1.000 C 0.000,0.448 0.448,0.000 1.000,0.000 Z M 1.000,8.000 L 23.000,8.000 C 23.552,8.000 24.000,8.448 24.000,9.000 L 24.000,11.000 C 24.000,11.552 23.552,12.000 23.000,12.000 L 1.000,12.000 C 0.448,12.000 0.000,11.552 0.000,11.000 L 0.000,9.000 C 0.000,8.448 0.448,8.000 1.000,8.000 Z M 1.000,16.000 L 23.000,16.000 C 23.5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HamburgerPathData {
            get {
                return ResourceManager.GetString("HamburgerPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 12.000,12.000 L 22.000,12.000 L 22.000,22.000 L 12.000,22.000 L 12.000,12.000 Z M 0.000,12.000 L 10.000,12.000 L 10.000,22.000 L 0.000,22.000 L 0.000,12.000 Z M 12.000,0.000 L 22.000,0.000 L 22.000,10.000 L 12.000,10.000 L 12.000,0.000 Z M 0.000,0.000 L 10.000,0.000 L 10.000,10.000 L 0.000,10.000 L 0.000,0.000 Z.
        /// </summary>
        public static string LargeThumbnailViewPathData {
            get {
                return ResourceManager.GetString("LargeThumbnailViewPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 8.000,16.000 L 22.000,16.000 L 22.000,22.000 L 8.000,22.000 L 8.000,16.000 Z M 8.000,8.000 L 22.000,8.000 L 22.000,14.000 L 8.000,14.000 L 8.000,8.000 Z M 8.000,0.000 L 22.000,0.000 L 22.000,6.000 L 8.000,6.000 L 8.000,0.000 Z M 0.000,0.000 L 6.000,0.000 L 6.000,6.000 L 0.000,6.000 L 0.000,0.000 Z M 0.000,16.000 L 6.000,16.000 L 6.000,22.000 L 0.000,22.000 L 0.000,16.000 Z M 0.000,8.000 L 6.000,8.000 L 6.000,14.000 L 0.000,14.000 L 0.000,8.000 Z.
        /// </summary>
        public static string ListViewPathData {
            get {
                return ResourceManager.GetString("ListViewPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 17.725,16.615 L 16.168,16.615 C 15.965,16.615 15.802,16.450 15.802,16.246 L 15.802,11.419 C 15.802,11.378 15.752,11.357 15.723,11.387 L 12.427,14.709 C 12.140,14.997 11.676,14.997 11.390,14.709 L 8.093,11.387 C 8.065,11.357 8.015,11.378 8.015,11.419 L 8.015,16.246 C 8.015,16.450 7.851,16.615 7.649,16.615 L 6.092,16.615 C 5.889,16.615 5.725,16.450 5.725,16.246 L 5.725,7.754 C 5.725,7.550 5.889,7.385 6.092,7.385 L 7.162,7.385 C 7.356,7.385 7.543,7.462 7.680,7.601 L 11.779,11.731 C 11.850,11.803 11.966,11 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MegaHomeLogoData {
            get {
                return ResourceManager.GetString("MegaHomeLogoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 22.500,30.000 C 18.360,30.000 15.000,26.640 15.000,22.500 C 15.000,18.360 18.360,15.000 22.500,15.000 C 26.640,15.000 30.000,18.360 30.000,22.500 C 30.000,26.640 26.640,30.000 22.500,30.000 Z M 41.995,18.000 L 38.370,18.000 C 38.010,16.755 37.515,15.570 36.900,14.461 L 39.468,11.893 C 40.644,10.718 40.644,8.813 39.478,7.647 L 37.353,5.522 C 36.183,4.352 34.285,4.354 33.107,5.532 L 30.539,8.100 C 29.430,7.485 28.245,6.990 27.000,6.630 L 27.000,3.005 C 27.000,1.345 25.653,0.000 24.003,0.000 L 20.997,0.00 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SettingsPathData {
            get {
                return ResourceManager.GetString("SettingsPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 43.500,3.000 L 25.500,3.000 L 22.500,0.000 L 1.500,0.000 C 0.675,0.000 0.000,0.675 0.000,1.500 L 0.000,6.000 L 45.000,6.000 L 45.000,4.500 C 45.000,3.675 44.325,3.000 43.500,3.000 Z M 0.000,34.500 C 0.000,35.325 0.675,36.000 1.500,36.000 L 43.500,36.000 C 44.325,36.000 45.000,35.325 45.000,34.500 L 45.000,7.000 L 0.000,7.000 L 0.000,34.500 Z M 10.500,30.000 L 5.279,30.000 C 4.860,30.000 4.500,29.640 4.500,29.220 L 4.500,28.980 C 4.500,28.980 4.500,27.120 4.800,26.805 C 5.235,26.370 9.000,24.630 9.707,2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SharedItemsPathData {
            get {
                return ResourceManager.GetString("SharedItemsPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 16.000,0.000 L 22.000,0.000 L 22.000,6.000 L 16.000,6.000 L 16.000,0.000 Z M 8.000,0.000 L 14.000,0.000 L 14.000,6.000 L 8.000,6.000 L 8.000,0.000 Z M 16.000,8.000 L 22.000,8.000 L 22.000,14.000 L 16.000,14.000 L 16.000,8.000 Z M 8.000,8.000 L 14.000,8.000 L 14.000,14.000 L 8.000,14.000 L 8.000,8.000 Z M 16.000,16.000 L 22.000,16.000 L 22.000,22.000 L 16.000,22.000 L 16.000,16.000 Z M 8.000,16.000 L 14.000,16.000 L 14.000,22.000 L 8.000,22.000 L 8.000,16.000 Z M 0.000,0.000 L 6.000,0.000 L 6.000,6.000  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SmallThumbnailViewPathData {
            get {
                return ResourceManager.GetString("SmallThumbnailViewPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 29.000,34.000 L 20.000,24.000 L 26.000,24.000 L 26.000,16.000 L 32.000,16.000 L 32.000,24.000 L 38.000,24.000 L 29.000,34.000 Z M 18.000,26.000 L 12.000,26.000 L 12.000,20.000 L 6.000,20.000 L 15.000,10.000 L 24.000,20.000 L 18.000,20.000 L 18.000,26.000 Z M 22.000,0.000 C 9.850,0.000 0.000,9.850 0.000,22.000 C 0.000,34.150 9.850,44.000 22.000,44.000 C 34.150,44.000 44.000,34.150 44.000,22.000 C 44.000,9.850 34.150,0.000 22.000,0.000 Z.
        /// </summary>
        public static string TransfersPathData {
            get {
                return ResourceManager.GetString("TransfersPathData", resourceCulture);
            }
        }
    }
}
